/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package loymax.sdk.models

import loymax.sdk.models.CurrencyInfoModel

import com.squareup.moshi.Json

/**
 * Информация о балансе счета.
 *
 * @param currency 
 * @param balance Баланс счета клиента.
 * @param notActivated Неактивированные бонусы.
 * @param accumulated Бонусов получено.
 * @param paid Бонусов потрачено.
 */

data class AccountBalanceModel (

    @Json(name = "currency")
    var currency: CurrencyInfoModel? = null,

    /* Баланс счета клиента. */
    @Json(name = "balance")
    var balance: kotlin.Double? = null,

    /* Неактивированные бонусы. */
    @Json(name = "notActivated")
    var notActivated: kotlin.Double? = null,

    /* Бонусов получено. */
    @Json(name = "accumulated")
    var accumulated: kotlin.Double? = null,

    /* Бонусов потрачено. */
    @Json(name = "paid")
    var paid: kotlin.Double? = null

)

