/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package loymax.sdk.models

import loymax.sdk.models.CurrencyInfoModel

import com.squareup.moshi.Json

/**
 * Модель дебетового счета.
 *
 * @param amount Текущая сумма на счете.
 * @param creditAmount Кредит по счету.
 * @param currency 
 * @param block Признак блокировки счета (true — заблокирован, false — не заблокирован).
 */

data class AccountViewModel (

    /* Текущая сумма на счете. */
    @Json(name = "amount")
    var amount: kotlin.Double? = null,

    /* Кредит по счету. */
    @Json(name = "creditAmount")
    var creditAmount: kotlin.Double? = null,

    @Json(name = "currency")
    var currency: CurrencyInfoModel? = null,

    /* Признак блокировки счета (true — заблокирован, false — не заблокирован). */
    @Json(name = "block")
    var block: kotlin.Boolean? = null

)

