/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package loymax.sdk.models


import com.squareup.moshi.Json

/**
 * Модель для типа действия.
 *
 * @param logicalName Логическое имя действия.
 * @param isDeleted Удаленный тип.
 */

data class ActionTypeViewModel (

    /* Логическое имя действия. */
    @Json(name = "logicalName")
    var logicalName: kotlin.String? = null,

    /* Удаленный тип. */
    @Json(name = "isDeleted")
    var isDeleted: kotlin.Boolean? = null

)

