/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package loymax.sdk.models

import loymax.sdk.models.MetavariableModel
import loymax.sdk.models.PositionModel

import com.squareup.moshi.Json

/**
 * Фильтр для списка счетов кассы.
 *
 * @param position 
 * @param `value` Результат действия.
 * @param resultUid Идентификатор результат.
 * @param metavariables Метапеременные результата.
 */

data class ActionResultModel (

    @Json(name = "position")
    var position: PositionModel? = null,

    /* Результат действия. */
    @Json(name = "value")
    var `value`: kotlin.String? = null,

    /* Идентификатор результат. */
    @Json(name = "resultUid")
    var resultUid: java.util.UUID? = null,

    /* Метапеременные результата. */
    @Json(name = "metavariables")
    var metavariables: kotlin.collections.MutableList<MetavariableModel>? = null

)

