/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package loymax.sdk.models


import com.squareup.moshi.Json

/**
 * Информация об адресе.
 *
 * @param city Город.
 * @param street Улица.
 * @param house Дом.
 * @param building Строение.
 * @param flat Квартира.
 */

data class AddressInfo (

    /* Город. */
    @Json(name = "city")
    var city: kotlin.String? = null,

    /* Улица. */
    @Json(name = "street")
    var street: kotlin.String? = null,

    /* Дом. */
    @Json(name = "house")
    var house: kotlin.String? = null,

    /* Строение. */
    @Json(name = "building")
    var building: kotlin.String? = null,

    /* Квартира. */
    @Json(name = "flat")
    var flat: kotlin.String? = null

)

