/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package loymax.sdk.models


import com.squareup.moshi.Json

/**
 * Фильтр по атрибуту.
 *
 * @param name Название атрибута.
 */

data class AttributeDto (

    /* Название атрибута. */
    @Json(name = "name")
    var name: kotlin.String? = null

)

