/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package loymax.sdk.models

import loymax.sdk.models.AttributeMappingModel
import loymax.sdk.models.AttributeRestrictionModel
import loymax.sdk.models.AttributeType

import com.squareup.moshi.Json

/**
 * 
 *
 * @param id 
 * @param logicalName 
 * @param name 
 * @param attributeType 
 * @param restrictions 
 * @param mappings 
 */

data class AttributeModel (

    @Json(name = "id")
    var id: kotlin.Int? = null,

    @Json(name = "logicalName")
    var logicalName: kotlin.String? = null,

    @Json(name = "name")
    var name: kotlin.String? = null,

    @Json(name = "attributeType")
    var attributeType: AttributeType? = null,

    @Json(name = "restrictions")
    var restrictions: kotlin.collections.MutableList<AttributeRestrictionModel>? = null,

    @Json(name = "mappings")
    var mappings: kotlin.collections.MutableList<AttributeMappingModel>? = null

)

