/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package loymax.sdk.models


import com.squareup.moshi.Json

/**
 * 
 *
 * Values: STRING,BOOLEAN,NUMERIC,DATE_TIME,IMAGE,VIDEO,HTML,DICTIONARY,MECHANT
 */

enum class AttributeType(val value: kotlin.String) {

    @Json(name = "String")
    STRING("String"),

    @Json(name = "Boolean")
    BOOLEAN("Boolean"),

    @Json(name = "Numeric")
    NUMERIC("Numeric"),

    @Json(name = "DateTime")
    DATE_TIME("DateTime"),

    @Json(name = "Image")
    IMAGE("Image"),

    @Json(name = "Video")
    VIDEO("Video"),

    @Json(name = "Html")
    HTML("Html"),

    @Json(name = "Dictionary")
    DICTIONARY("Dictionary"),

    @Json(name = "Mechant")
    MECHANT("Mechant");

    /**
     * Override toString() to avoid using the enum variable name as the value, and instead use
     * the actual value defined in the API spec file.
     *
     * This solves a problem when the variable name and its value are different, and ensures that
     * the client sends the correct enum values to the server always.
     */
    override fun toString(): String = value

    companion object {
        /**
         * Converts the provided [data] to a [String] on success, null otherwise.
         */
        fun encode(data: kotlin.Any?): kotlin.String? = if (data is AttributeType) "$data" else null

        /**
         * Returns a valid [AttributeType] for [data], null otherwise.
         */
        fun decode(data: kotlin.Any?): AttributeType? = data?.let {
          val normalizedData = "$it".lowercase()
          values().firstOrNull { value ->
            it == value || normalizedData == "$value".lowercase()
          }
        }
    }
}

