/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package loymax.sdk.models


import com.squareup.moshi.Json

/**
 * Базовый класс для атрибутов.
 *
 * @param id Идентификатор.
 * @param name Имя.
 * @param order Порядковый номер.
 * @param logicalName Логическое имя.
 * @param historyIsRecorded История записывается.
 */

data class BaseUserAttributeViewModel (

    /* Идентификатор. */
    @Json(name = "id")
    var id: kotlin.Int? = null,

    /* Имя. */
    @Json(name = "name")
    var name: kotlin.String? = null,

    /* Порядковый номер. */
    @Json(name = "order")
    var order: kotlin.Int? = null,

    /* Логическое имя. */
    @Json(name = "logicalName")
    var logicalName: kotlin.String? = null,

    /* История записывается. */
    @Json(name = "historyIsRecorded")
    var historyIsRecorded: kotlin.Boolean? = null

)

