/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package loymax.sdk.models

import loymax.sdk.models.BatchOperationsQueueInfo
import loymax.sdk.models.BatchState
import loymax.sdk.models.BatchType
import loymax.sdk.models.CreatorModel
import loymax.sdk.models.CurrencyViewModel
import loymax.sdk.models.LegalViewModel
import loymax.sdk.models.LifeTimeDefinitionViewModel
import loymax.sdk.models.MarketingCampaignSimpleViewModel
import loymax.sdk.models.OpErrorHandlingType
import loymax.sdk.models.OperationDataModel
import loymax.sdk.models.PartnerLoyaltyProgramModel
import loymax.sdk.models.PartnerViewModel
import loymax.sdk.models.TargetGroupBriefViewModel

import com.squareup.moshi.Json

/**
 * Модель данных для пакетных начислений/списаний.
 *
 * @param id Внутренний идентификатор пакетного начисления/списания.
 * @param creationDate Дата создания.
 * @param description Описание начисления/списания.
 * @param internalDescription Системное описание начисления/списания.
 * @param type 
 * @param state 
 * @param legal 
 * @param deferredOperationsAmmountSum Сумма начисления/списания.
 * @param loyaltyProgram 
 * @param partner 
 * @param marketingCampaign 
 * @param creator 
 * @param errorHandlingType 
 * @param operations Список операций.
 * @param queueInfo 
 * @param lifeTimeDefinition 
 * @param currency 
 * @param targetGroup 
 */

data class BatchOperationsViewModel (

    /* Внутренний идентификатор пакетного начисления/списания. */
    @Json(name = "id")
    var id: kotlin.Int? = null,

    /* Дата создания. */
    @Json(name = "creationDate")
    var creationDate: java.time.OffsetDateTime? = null,

    /* Описание начисления/списания. */
    @Json(name = "description")
    var description: kotlin.String? = null,

    /* Системное описание начисления/списания. */
    @Json(name = "internalDescription")
    var internalDescription: kotlin.String? = null,

    @Json(name = "type")
    var type: BatchType? = null,

    @Json(name = "state")
    var state: BatchState? = null,

    @Json(name = "legal")
    var legal: LegalViewModel? = null,

    /* Сумма начисления/списания. */
    @Json(name = "deferredOperationsAmmountSum")
    var deferredOperationsAmmountSum: kotlin.Double? = null,

    @Json(name = "loyaltyProgram")
    var loyaltyProgram: PartnerLoyaltyProgramModel? = null,

    @Json(name = "partner")
    var partner: PartnerViewModel? = null,

    @Json(name = "marketingCampaign")
    var marketingCampaign: MarketingCampaignSimpleViewModel? = null,

    @Json(name = "creator")
    var creator: CreatorModel? = null,

    @Json(name = "errorHandlingType")
    var errorHandlingType: OpErrorHandlingType? = null,

    /* Список операций. */
    @Json(name = "operations")
    var operations: kotlin.collections.MutableList<OperationDataModel>? = null,

    @Json(name = "queueInfo")
    var queueInfo: BatchOperationsQueueInfo? = null,

    @Json(name = "lifeTimeDefinition")
    var lifeTimeDefinition: LifeTimeDefinitionViewModel? = null,

    @Json(name = "currency")
    var currency: CurrencyViewModel? = null,

    @Json(name = "targetGroup")
    var targetGroup: TargetGroupBriefViewModel? = null

)

