/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package loymax.sdk.models

import loymax.sdk.models.BatchState

import com.squareup.moshi.Json

/**
 * 
 *
 * @param id 
 * @param hasElements 
 * @param state 
 * @param allOperationCount 
 * @param completedOperationCount 
 * @param errorOperationCount 
 */

data class BatchOperationsQueueInfo (

    @Json(name = "id")
    var id: kotlin.Int? = null,

    @Json(name = "hasElements")
    var hasElements: kotlin.Boolean? = null,

    @Json(name = "state")
    var state: BatchState? = null,

    @Json(name = "allOperationCount")
    var allOperationCount: kotlin.Int? = null,

    @Json(name = "completedOperationCount")
    var completedOperationCount: kotlin.Int? = null,

    @Json(name = "errorOperationCount")
    var errorOperationCount: kotlin.Int? = null

)

