/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package loymax.sdk.models

import loymax.sdk.models.BatchState
import loymax.sdk.models.CreatorModel

import com.squareup.moshi.Json

/**
 * Модель пакетного обновления атрибутов клиентов.
 *
 * @param id Внутренний идентификатор пакетного обновления.
 * @param creator 
 * @param creationDate Дата создания.
 * @param description Описание пакетного обновления.
 * @param state 
 * @param supportNullable Поддерживается ли замена пустых значений атрибута на \"null\" (true — да, false — нет).
 */

data class BatchAttributeUpdateModel (

    /* Внутренний идентификатор пакетного обновления. */
    @Json(name = "id")
    var id: kotlin.Int? = null,

    @Json(name = "creator")
    var creator: CreatorModel? = null,

    /* Дата создания. */
    @Json(name = "creationDate")
    var creationDate: java.time.OffsetDateTime? = null,

    /* Описание пакетного обновления. */
    @Json(name = "description")
    var description: kotlin.String? = null,

    @Json(name = "state")
    var state: BatchState? = null,

    /* Поддерживается ли замена пустых значений атрибута на \"null\" (true — да, false — нет). */
    @Json(name = "supportNullable")
    var supportNullable: kotlin.Boolean? = null

)

