/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package loymax.sdk.models

import loymax.sdk.models.BirthdayFilterType

import com.squareup.moshi.Json

/**
 * Фильтр \"День рождения\".
 *
 * @param name Имя фильтра.
 * @param processParameters Параметры обработки.
 * @param type 
 * @param daysBefore Дней до.
 * @param daysAfter Дней после.
 */

data class BirthDayFilterDto (

    /* Имя фильтра. */
    @Json(name = "name")
    var name: kotlin.String? = null,

    /* Параметры обработки. */
    @Json(name = "processParameters")
    var processParameters: kotlin.String? = null,

    @Json(name = "type")
    var type: BirthdayFilterType? = null,

    /* Дней до. */
    @Json(name = "daysBefore")
    var daysBefore: kotlin.Int? = null,

    /* Дней после. */
    @Json(name = "daysAfter")
    var daysAfter: kotlin.Int? = null

)

