/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package loymax.sdk.models

import loymax.sdk.models.RepositoryCalculatorType

import com.squareup.moshi.Json

/**
 * Вью модель для Калкулятора.
 *
 * @param id Идентификатор.
 * @param name Наименование.
 * @param calculatorType 
 */

data class CalculatorViewModel (

    /* Идентификатор. */
    @Json(name = "id")
    var id: kotlin.Int? = null,

    /* Наименование. */
    @Json(name = "name")
    var name: kotlin.String? = null,

    @Json(name = "calculatorType")
    var calculatorType: RepositoryCalculatorType? = null

)

