/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package loymax.sdk.models

import loymax.sdk.models.CardEmissionPackingState
import loymax.sdk.models.CardEmissionType

import com.squareup.moshi.Json

/**
 * Фильтр для выпуска карт.
 *
 * @param from Начало выборки.
 * @param count Количество.
 * @param loyaltyPrograms Список ПЛ для фильтра по ПЛ.
 * @param nameText Текст содержащийся в описании.
 * @param packingState 
 * @param activationType Тип активации.
 * @param cardEmissionType 
 */

data class CardsFilter (

    /* Начало выборки. */
    @Json(name = "from")
    var from: kotlin.Int? = null,

    /* Количество. */
    @Json(name = "count")
    var count: kotlin.Int? = null,

    /* Список ПЛ для фильтра по ПЛ. */
    @Json(name = "loyaltyPrograms")
    var loyaltyPrograms: kotlin.collections.MutableList<kotlin.Int>? = null,

    /* Текст содержащийся в описании. */
    @Json(name = "nameText")
    var nameText: kotlin.String? = null,

    @Json(name = "packingState")
    var packingState: CardEmissionPackingState? = null,

    /* Тип активации. */
    @Json(name = "activationType")
    var activationType: kotlin.Boolean? = null,

    @Json(name = "cardEmissionType")
    var cardEmissionType: CardEmissionType? = null

)

