/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package loymax.sdk.models

import loymax.sdk.models.ImageViewModel

import com.squareup.moshi.Json

/**
 * Информация о категории карты.
 *
 * @param id Ифентификатор.
 * @param title Название.
 * @param logicalName Логическое имя (для отображения изобрабражения типа карты в ЛК).
 * @param images Изображения.
 */

data class CardCategoryInfoBriefModel (

    /* Ифентификатор. */
    @Json(name = "id")
    var id: kotlin.Int? = null,

    /* Название. */
    @Json(name = "title")
    var title: kotlin.String? = null,

    /* Логическое имя (для отображения изобрабражения типа карты в ЛК). */
    @Json(name = "logicalName")
    var logicalName: kotlin.String? = null,

    /* Изображения. */
    @Json(name = "images")
    var images: kotlin.collections.MutableList<ImageViewModel>? = null

)

