/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package loymax.sdk.models


import com.squareup.moshi.Json

/**
 * View модель фильтра \"Список карт\".
 *
 * @param id 
 * @param name 
 * @param isDeletedFilterType 
 * @param processParameters 
 * @param cardsNumbers Список номеров выбранных карт.
 * @param ignoreDeletedCards Игнорировать удаленные карты.
 */

data class CardListFilterViewModel (

    @Json(name = "id")
    var id: kotlin.Int? = null,

    @Json(name = "name")
    var name: kotlin.String? = null,

    @Json(name = "isDeletedFilterType")
    var isDeletedFilterType: kotlin.Boolean? = null,

    @Json(name = "processParameters")
    var processParameters: kotlin.String? = null,

    /* Список номеров выбранных карт. */
    @Json(name = "cardsNumbers")
    var cardsNumbers: kotlin.collections.MutableList<kotlin.String>? = null,

    /* Игнорировать удаленные карты. */
    @Json(name = "ignoreDeletedCards")
    var ignoreDeletedCards: kotlin.Boolean? = null

)

