/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package loymax.sdk.models


import com.squareup.moshi.Json

/**
 * Информация о возможности выполнять действия с картой.
 *
 * @param canBlock Возможность заблокировать карту.
 * @param canReplace Возможность заменить карту.
 */

data class CardActionAccessInfo (

    /* Возможность заблокировать карту. */
    @Json(name = "canBlock")
    var canBlock: kotlin.Boolean? = null,

    /* Возможность заменить карту. */
    @Json(name = "canReplace")
    var canReplace: kotlin.Boolean? = null

)

