/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package loymax.sdk.models

import loymax.sdk.models.CardType

import com.squareup.moshi.Json

/**
 * Фильтр \"Тип карты\".
 *
 * @param name Имя фильтра.
 * @param processParameters Параметры обработки.
 * @param cardTypes Список типов карт.
 */

data class CardTypeFilterDto (

    /* Имя фильтра. */
    @Json(name = "name")
    var name: kotlin.String? = null,

    /* Параметры обработки. */
    @Json(name = "processParameters")
    var processParameters: kotlin.String? = null,

    /* Список типов карт. */
    @Json(name = "cardTypes")
    var cardTypes: kotlin.collections.MutableList<CardType>? = null

)

