/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package loymax.sdk.models


import com.squareup.moshi.Json

/**
 * Модель карты.
 *
 * @param cardNumber Номер карты.
 */

data class CardViewModel (

    /* Номер карты. */
    @Json(name = "cardNumber")
    var cardNumber: kotlin.String? = null

)

