/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package loymax.sdk.models


import com.squareup.moshi.Json

/**
 * Фильтр \"Карта из указанного выпуска\".
 *
 * @param name Имя фильтра.
 * @param processParameters Параметры обработки.
 * @param emissionIds Выбранные выпуски.
 */

data class CardEmissionFilterDto (

    /* Имя фильтра. */
    @Json(name = "name")
    var name: kotlin.String? = null,

    /* Параметры обработки. */
    @Json(name = "processParameters")
    var processParameters: kotlin.String? = null,

    /* Выбранные выпуски. */
    @Json(name = "emissionIds")
    var emissionIds: kotlin.collections.MutableList<kotlin.Int>? = null

)

