/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package loymax.sdk.models


import com.squareup.moshi.Json

/**
 * Фильтр \"Список карт\".
 *
 * @param name Имя фильтра.
 * @param processParameters Параметры обработки.
 * @param cards Номера выбранных карт.
 */

data class CardListFilterDto (

    /* Имя фильтра. */
    @Json(name = "name")
    var name: kotlin.String? = null,

    /* Параметры обработки. */
    @Json(name = "processParameters")
    var processParameters: kotlin.String? = null,

    /* Номера выбранных карт. */
    @Json(name = "cards")
    var cards: kotlin.collections.MutableList<kotlin.String>? = null

)

