/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package loymax.sdk.models


import com.squareup.moshi.Json

/**
 * Модель для обновления пароля.
 *
 * @param oldPassword Старый пароль.
 * @param newPassword Новый пароль.
 */

data class ChangePasswordModel (

    /* Старый пароль. */
    @Json(name = "oldPassword")
    var oldPassword: kotlin.String? = null,

    /* Новый пароль. */
    @Json(name = "newPassword")
    var newPassword: kotlin.String? = null

)

