/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package loymax.sdk.models

import loymax.sdk.models.ActionTypeViewModel
import loymax.sdk.models.CurrencyViewModel
import loymax.sdk.models.LegalViewModel
import loymax.sdk.models.LifeTimeDefinitionBaseViewModel

import com.squareup.moshi.Json

/**
 * Модель для редактирования действия начисления дополнительных бонусов.
 *
 * @param actionId Id действия. Если указан, редактируется действие, иначе создается новое.
 * @param actionType 
 * @param order Порядок действия.
 * @param amount Значение.
 * @param lifeTimeDefinition 
 * @param legal 
 * @param currency 
 */

data class ChargingActionViewModel (

    /* Id действия. Если указан, редактируется действие, иначе создается новое. */
    @Json(name = "actionId")
    var actionId: kotlin.Int? = null,

    @Json(name = "actionType")
    var actionType: ActionTypeViewModel? = null,

    /* Порядок действия. */
    @Json(name = "order")
    var order: kotlin.Int? = null,

    /* Значение. */
    @Json(name = "amount")
    var amount: kotlin.String? = null,

    @Json(name = "lifeTimeDefinition")
    var lifeTimeDefinition: LifeTimeDefinitionBaseViewModel? = null,

    @Json(name = "legal")
    var legal: LegalViewModel? = null,

    @Json(name = "currency")
    var currency: CurrencyViewModel? = null

)

