/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package loymax.sdk.models


import com.squareup.moshi.Json

/**
 * Тип сортировки товаров при покупке.
 *
 * Values: POSITION_ASCENDING,POSITION_DESCENDING,PRICE_ASCENDING,PRICE_DESCENDING
 */

enum class ChequeGoodsSortType(val value: kotlin.String) {

    @Json(name = "PositionAscending")
    POSITION_ASCENDING("PositionAscending"),

    @Json(name = "PositionDescending")
    POSITION_DESCENDING("PositionDescending"),

    @Json(name = "PriceAscending")
    PRICE_ASCENDING("PriceAscending"),

    @Json(name = "PriceDescending")
    PRICE_DESCENDING("PriceDescending");

    /**
     * Override toString() to avoid using the enum variable name as the value, and instead use
     * the actual value defined in the API spec file.
     *
     * This solves a problem when the variable name and its value are different, and ensures that
     * the client sends the correct enum values to the server always.
     */
    override fun toString(): String = value

    companion object {
        /**
         * Converts the provided [data] to a [String] on success, null otherwise.
         */
        fun encode(data: kotlin.Any?): kotlin.String? = if (data is ChequeGoodsSortType) "$data" else null

        /**
         * Returns a valid [ChequeGoodsSortType] for [data], null otherwise.
         */
        fun decode(data: kotlin.Any?): ChequeGoodsSortType? = data?.let {
          val normalizedData = "$it".lowercase()
          values().firstOrNull { value ->
            it == value || normalizedData == "$value".lowercase()
          }
        }
    }
}

