/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package loymax.sdk.models

import loymax.sdk.models.ChequeGoodsFilterType
import loymax.sdk.models.FilterOperation
import loymax.sdk.models.GoodsGroupViewModel

import com.squareup.moshi.Json

/**
 * ViewModel для фильтра \"Ограничение на товар\".
 *
 * @param id 
 * @param name 
 * @param isDeletedFilterType 
 * @param processParameters 
 * @param goodsGroups Список выбранных групп товаров.
 * @param personalOfferAttributeId Идентификатор атрибута \"Персональное предложение\".
 * @param type 
 * @param operation 
 * @param `value` Значение для операции.
 * @param counterId Идентификатор счетчика.
 */

data class ChequeGoodsLimitWithCounterFilterViewModel (

    @Json(name = "id")
    var id: kotlin.Int? = null,

    @Json(name = "name")
    var name: kotlin.String? = null,

    @Json(name = "isDeletedFilterType")
    var isDeletedFilterType: kotlin.Boolean? = null,

    @Json(name = "processParameters")
    var processParameters: kotlin.String? = null,

    /* Список выбранных групп товаров. */
    @Json(name = "goodsGroups")
    var goodsGroups: kotlin.collections.MutableList<GoodsGroupViewModel>? = null,

    /* Идентификатор атрибута \"Персональное предложение\". */
    @Json(name = "personalOfferAttributeId")
    var personalOfferAttributeId: kotlin.Int? = null,

    @Json(name = "type")
    var type: ChequeGoodsFilterType? = null,

    @Json(name = "operation")
    var operation: FilterOperation? = null,

    /* Значение для операции. */
    @Json(name = "value")
    var `value`: kotlin.Double? = null,

    /* Идентификатор счетчика. */
    @Json(name = "counterId")
    var counterId: kotlin.Int? = null

)

