/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package loymax.sdk.models


import com.squareup.moshi.Json

/**
 * Фильтр \"Дополнительная информация по чековой позиции\".
 *
 * @param name Имя фильтра.
 * @param processParameters Параметры обработки.
 * @param parameterName Имя параметра.
 * @param expectedValues Ожидаемые значения параметра.
 * @param isNegative Отрицание (значение параметра не должно быть среди ожидаемых).
 */

data class ChequePositionParameterFilterDto (

    /* Имя фильтра. */
    @Json(name = "name")
    var name: kotlin.String? = null,

    /* Параметры обработки. */
    @Json(name = "processParameters")
    var processParameters: kotlin.String? = null,

    /* Имя параметра. */
    @Json(name = "parameterName")
    var parameterName: kotlin.String? = null,

    /* Ожидаемые значения параметра. */
    @Json(name = "expectedValues")
    var expectedValues: kotlin.collections.MutableList<kotlin.String>? = null,

    /* Отрицание (значение параметра не должно быть среди ожидаемых). */
    @Json(name = "isNegative")
    var isNegative: kotlin.Boolean? = null

)

