/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package loymax.sdk.models


import com.squareup.moshi.Json

/**
 * Модель обновления данных общего атрибута.
 *
 * @param xPath JSONPath для обновления данных.
 * @param `value` Значение атрибута или свойства JSON.
 */

data class CommonAttributeValueModel (

    /* JSONPath для обновления данных. */
    @Json(name = "xPath")
    var xPath: kotlin.String? = null,

    /* Значение атрибута или свойства JSON. */
    @Json(name = "value")
    var `value`: kotlin.String? = null

)

