/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package loymax.sdk.models

import loymax.sdk.models.PartnerModel

import com.squareup.moshi.Json

/**
 * Модель представления категории рекламных материалов.
 *
 * @param id Идентификатор.
 * @param name Название.
 * @param logicalName Логическое название.
 * @param partner 
 * @param isArchived Признак архивирования категории.
 */

data class CommunicationOfferCategoryViewModel (

    /* Идентификатор. */
    @Json(name = "id")
    var id: kotlin.Int? = null,

    /* Название. */
    @Json(name = "name")
    var name: kotlin.String? = null,

    /* Логическое название. */
    @Json(name = "logicalName")
    var logicalName: kotlin.String? = null,

    @Json(name = "partner")
    var partner: PartnerModel? = null,

    /* Признак архивирования категории. */
    @Json(name = "isArchived")
    var isArchived: kotlin.Boolean? = null

)

