/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package loymax.sdk.models


import com.squareup.moshi.Json

/**
 * 
 *
 * Values: ORIGINAL,PERSONAL_GOODS,PERSONAL_OFFER,ALL
 */

enum class CommunicationOfferType(val value: kotlin.String) {

    @Json(name = "Original")
    ORIGINAL("Original"),

    @Json(name = "PersonalGoods")
    PERSONAL_GOODS("PersonalGoods"),

    @Json(name = "PersonalOffer")
    PERSONAL_OFFER("PersonalOffer"),

    @Json(name = "All")
    ALL("All");

    /**
     * Override toString() to avoid using the enum variable name as the value, and instead use
     * the actual value defined in the API spec file.
     *
     * This solves a problem when the variable name and its value are different, and ensures that
     * the client sends the correct enum values to the server always.
     */
    override fun toString(): String = value

    companion object {
        /**
         * Converts the provided [data] to a [String] on success, null otherwise.
         */
        fun encode(data: kotlin.Any?): kotlin.String? = if (data is CommunicationOfferType) "$data" else null

        /**
         * Returns a valid [CommunicationOfferType] for [data], null otherwise.
         */
        fun decode(data: kotlin.Any?): CommunicationOfferType? = data?.let {
          val normalizedData = "$it".lowercase()
          values().firstOrNull { value ->
            it == value || normalizedData == "$value".lowercase()
          }
        }
    }
}

