/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package loymax.sdk.models


import com.squareup.moshi.Json

/**
 * Информация о скрипте.
 *
 * @param id Идентификатор скрипта.
 * @param executionDate Дата исполнения скрипта.
 * @param configDeployId Идентификатор деплоя, в котором выполнился скрипт.
 * @param duration Время выполнения в мс.
 * @param dbName Название БД.
 */

data class ConfigurationScriptViewModel (

    /* Идентификатор скрипта. */
    @Json(name = "id")
    var id: kotlin.String? = null,

    /* Дата исполнения скрипта. */
    @Json(name = "executionDate")
    var executionDate: java.time.OffsetDateTime? = null,

    /* Идентификатор деплоя, в котором выполнился скрипт. */
    @Json(name = "configDeployId")
    var configDeployId: java.util.UUID? = null,

    /* Время выполнения в мс. */
    @Json(name = "duration")
    var duration: kotlin.Int? = null,

    /* Название БД. */
    @Json(name = "dbName")
    var dbName: kotlin.String? = null

)

