/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package loymax.sdk.models


import com.squareup.moshi.Json

/**
 * Тип значения.
 *
 * Values: INTEGER,STRING,CURRENCY_EXTERNAL_ID,OFFER_CATEGORY,PUSH_GATEWAY
 */

enum class ConfigValueType(val value: kotlin.String) {

    @Json(name = "Integer")
    INTEGER("Integer"),

    @Json(name = "String")
    STRING("String"),

    @Json(name = "CurrencyExternalId")
    CURRENCY_EXTERNAL_ID("CurrencyExternalId"),

    @Json(name = "OfferCategory")
    OFFER_CATEGORY("OfferCategory"),

    @Json(name = "PushGateway")
    PUSH_GATEWAY("PushGateway");

    /**
     * Override toString() to avoid using the enum variable name as the value, and instead use
     * the actual value defined in the API spec file.
     *
     * This solves a problem when the variable name and its value are different, and ensures that
     * the client sends the correct enum values to the server always.
     */
    override fun toString(): String = value

    companion object {
        /**
         * Converts the provided [data] to a [String] on success, null otherwise.
         */
        fun encode(data: kotlin.Any?): kotlin.String? = if (data is ConfigValueType) "$data" else null

        /**
         * Returns a valid [ConfigValueType] for [data], null otherwise.
         */
        fun decode(data: kotlin.Any?): ConfigValueType? = data?.let {
          val normalizedData = "$it".lowercase()
          values().firstOrNull { value ->
            it == value || normalizedData == "$value".lowercase()
          }
        }
    }
}

