/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package loymax.sdk.models


import com.squareup.moshi.Json

/**
 * Информация о плагине.
 *
 * @param id Идентификатор плагина.
 * @param plugin Название плагина.
 * @param version Версия плагина.
 * @param deployId Идентификатор деплоя, в котором используется плагин.
 */

data class ConfigurationPluginViewModel (

    /* Идентификатор плагина. */
    @Json(name = "id")
    var id: kotlin.Int? = null,

    /* Название плагина. */
    @Json(name = "plugin")
    var plugin: kotlin.String? = null,

    /* Версия плагина. */
    @Json(name = "version")
    var version: kotlin.String? = null,

    /* Идентификатор деплоя, в котором используется плагин. */
    @Json(name = "deployId")
    var deployId: java.util.UUID? = null

)

