/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package loymax.sdk.models


import com.squareup.moshi.Json

/**
 * Фильтр для деплоя.
 *
 * @param fromDate Дата С.
 * @param toDate Дата По.
 * @param packageVersionSubstring Подстрока для поиска по версионности.
 * @param isSuccess Успешность выполнения.
 * @param authorSubstring Подстрока для поиска по автору.
 * @param externalId Внешний идентификатор.
 */

data class ConfigurationDeployFilter (

    /* Дата С. */
    @Json(name = "fromDate")
    var fromDate: java.time.OffsetDateTime? = null,

    /* Дата По. */
    @Json(name = "toDate")
    var toDate: java.time.OffsetDateTime? = null,

    /* Подстрока для поиска по версионности. */
    @Json(name = "packageVersionSubstring")
    var packageVersionSubstring: kotlin.String? = null,

    /* Успешность выполнения. */
    @Json(name = "isSuccess")
    var isSuccess: kotlin.Boolean? = null,

    /* Подстрока для поиска по автору. */
    @Json(name = "authorSubstring")
    var authorSubstring: kotlin.String? = null,

    /* Внешний идентификатор. */
    @Json(name = "externalId")
    var externalId: java.util.UUID? = null

)

