/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package loymax.sdk.models


import com.squareup.moshi.Json

/**
 * Информация о деплое.
 *
 * @param id Идентификатор деплоя.
 * @param packageVersion Версия пакета.
 * @param date Дата.
 * @param finishDate Дата завершения обновления.
 * @param author Автор.
 * @param isSuccess Успешность.
 * @param externalId Внешний идентификатор.
 */

data class ConfigurationDeployViewModel (

    /* Идентификатор деплоя. */
    @Json(name = "id")
    var id: kotlin.Int? = null,

    /* Версия пакета. */
    @Json(name = "packageVersion")
    var packageVersion: kotlin.String? = null,

    /* Дата. */
    @Json(name = "date")
    var date: java.time.OffsetDateTime? = null,

    /* Дата завершения обновления. */
    @Json(name = "finishDate")
    var finishDate: java.time.OffsetDateTime? = null,

    /* Автор. */
    @Json(name = "author")
    var author: kotlin.String? = null,

    /* Успешность. */
    @Json(name = "isSuccess")
    var isSuccess: kotlin.Boolean? = null,

    /* Внешний идентификатор. */
    @Json(name = "externalId")
    var externalId: java.util.UUID? = null

)

