/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package loymax.sdk.models


import com.squareup.moshi.Json

/**
 * Фильтр для плагинов.
 *
 * @param pluginSubstring Подстрока для поиска по названию плагина.
 * @param deployIdSubstring Подстрока для поиска по ID деплоя.
 */

data class ConfigurationPluginFilter (

    /* Подстрока для поиска по названию плагина. */
    @Json(name = "pluginSubstring")
    var pluginSubstring: kotlin.String? = null,

    /* Подстрока для поиска по ID деплоя. */
    @Json(name = "deployIdSubstring")
    var deployIdSubstring: kotlin.String? = null

)

