/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package loymax.sdk.models

import loymax.sdk.models.ActionTypeViewModel
import loymax.sdk.models.PaymentCorrectionTargets

import com.squareup.moshi.Json

/**
 * View модель действия \"Корректировка оплаты\".
 *
 * @param actionId Id действия. Если указан, редактируется действие, иначе создается новое.
 * @param actionType 
 * @param order Порядок действия.
 * @param roundValue Значение округления в копейках.
 * @param target 
 */

data class CorrectionPaymentActionViewModel (

    /* Id действия. Если указан, редактируется действие, иначе создается новое. */
    @Json(name = "actionId")
    var actionId: kotlin.Int? = null,

    @Json(name = "actionType")
    var actionType: ActionTypeViewModel? = null,

    /* Порядок действия. */
    @Json(name = "order")
    var order: kotlin.Int? = null,

    /* Значение округления в копейках. */
    @Json(name = "roundValue")
    var roundValue: kotlin.Int? = null,

    @Json(name = "target")
    var target: PaymentCorrectionTargets? = null

)

