/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package loymax.sdk.models

import loymax.sdk.models.CounterOperationType
import loymax.sdk.models.CounterValueTargetsModel

import com.squareup.moshi.Json

/**
 * Модель для обновления значения счетчика.
 *
 * @param targetsValues 
 * @param counterValueOperation 
 * @param expectedCurrentValue Текущее значение счетчика.
 * @param `value` Новое значение счетчика.
 * @param comment Комментарий.
 */

data class CounterValueSetModel (

    @Json(name = "targetsValues")
    var targetsValues: CounterValueTargetsModel? = null,

    @Json(name = "counterValueOperation")
    var counterValueOperation: CounterOperationType? = null,

    /* Текущее значение счетчика. */
    @Json(name = "expectedCurrentValue")
    var expectedCurrentValue: kotlin.Double? = null,

    /* Новое значение счетчика. */
    @Json(name = "value")
    var `value`: kotlin.Double? = null,

    /* Комментарий. */
    @Json(name = "comment")
    var comment: kotlin.String? = null

)

