/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package loymax.sdk.models


import com.squareup.moshi.Json

/**
 * Модель для параметров счетчика.
 *
 * @param eventDateTime Дата и время события.
 * @param sourceDateTime Исходные дата и время.
 * @param personId Пользователь системы.
 * @param cardId Карта.
 * @param partnerId Партнёр.
 * @param deviceId Устройство.
 * @param merchantId Магазин.
 * @param oAuthIdentifierInfo Пользователь социальной сети.
 * @param oAuthActivityType Тип пользовательской активноcти.
 * @param oAuthObjectId Объект социальной сети.
 * @param oAuthGroupId Группа социальной сети.
 * @param accountGroup Счет.
 * @param refundedPurchaseId Возвращенная покупка.
 * @param referralId Реферал.
 * @param purchaseId Покупка.
 * @param legalId Юр. лицо.
 * @param eventDay День события.
 * @param eventMonth Месяц события.
 * @param eventYear Год события.
 */

data class CounterValueTargetsModel (

    /* Дата и время события. */
    @Json(name = "eventDateTime")
    var eventDateTime: java.time.OffsetDateTime? = null,

    /* Исходные дата и время. */
    @Json(name = "sourceDateTime")
    var sourceDateTime: java.time.OffsetDateTime? = null,

    /* Пользователь системы. */
    @Json(name = "personId")
    var personId: kotlin.Int? = null,

    /* Карта. */
    @Json(name = "cardId")
    var cardId: kotlin.Int? = null,

    /* Партнёр. */
    @Json(name = "partnerId")
    var partnerId: kotlin.Int? = null,

    /* Устройство. */
    @Json(name = "deviceId")
    var deviceId: kotlin.Int? = null,

    /* Магазин. */
    @Json(name = "merchantId")
    var merchantId: kotlin.Int? = null,

    /* Пользователь социальной сети. */
    @Json(name = "oAuthIdentifierInfo")
    var oAuthIdentifierInfo: kotlin.String? = null,

    /* Тип пользовательской активноcти. */
    @Json(name = "oAuthActivityType")
    var oAuthActivityType: kotlin.String? = null,

    /* Объект социальной сети. */
    @Json(name = "oAuthObjectId")
    var oAuthObjectId: kotlin.String? = null,

    /* Группа социальной сети. */
    @Json(name = "oAuthGroupId")
    var oAuthGroupId: kotlin.String? = null,

    /* Счет. */
    @Json(name = "accountGroup")
    var accountGroup: kotlin.String? = null,

    /* Возвращенная покупка. */
    @Json(name = "refundedPurchaseId")
    var refundedPurchaseId: kotlin.Int? = null,

    /* Реферал. */
    @Json(name = "referralId")
    var referralId: kotlin.Int? = null,

    /* Покупка. */
    @Json(name = "purchaseId")
    var purchaseId: kotlin.String? = null,

    /* Юр. лицо. */
    @Json(name = "legalId")
    var legalId: kotlin.Int? = null,

    /* День события. */
    @Json(name = "eventDay")
    var eventDay: java.time.OffsetDateTime? = null,

    /* Месяц события. */
    @Json(name = "eventMonth")
    var eventMonth: java.time.OffsetDateTime? = null,

    /* Год события. */
    @Json(name = "eventYear")
    var eventYear: java.time.OffsetDateTime? = null

)

