/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package loymax.sdk.models

import loymax.sdk.models.ActionTypeViewModel
import loymax.sdk.models.CounterOperationType
import loymax.sdk.models.IncrementType
import loymax.sdk.models.OfferEventContextVariableViewModel

import com.squareup.moshi.Json

/**
 * Модель для редактирования действия \"Счётчик\".
 *
 * @param actionId Id действия. Если указан, редактируется действие, иначе создается новое.
 * @param actionType 
 * @param order Порядок действия.
 * @param counterId Привязанный счётчик.
 * @param targets Список моделей для счётчика.
 * @param increment Величина изменения счётчика.
 * @param incrementType 
 * @param variable 
 * @param operation 
 */

data class CounterActionViewModel (

    /* Id действия. Если указан, редактируется действие, иначе создается новое. */
    @Json(name = "actionId")
    var actionId: kotlin.Int? = null,

    @Json(name = "actionType")
    var actionType: ActionTypeViewModel? = null,

    /* Порядок действия. */
    @Json(name = "order")
    var order: kotlin.Int? = null,

    /* Привязанный счётчик. */
    @Json(name = "counterId")
    var counterId: kotlin.Int? = null,

    /* Список моделей для счётчика. */
    @Json(name = "targets")
    var targets: kotlin.collections.MutableList<kotlin.String>? = null,

    /* Величина изменения счётчика. */
    @Json(name = "increment")
    var increment: kotlin.Double? = null,

    @Json(name = "incrementType")
    var incrementType: IncrementType? = null,

    @Json(name = "variable")
    var variable: OfferEventContextVariableViewModel? = null,

    @Json(name = "operation")
    var operation: CounterOperationType? = null

)

