/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package loymax.sdk.models

import loymax.sdk.models.CounterValueTargetsModel

import com.squareup.moshi.Json

/**
 * Модель для значений счетчика.
 *
 * @param targetsValues 
 * @param `value` Значение счетчика.
 * @param hashes Идентификаторы значений счетчика.
 * @param updateDate Дата обновления счетчика.
 */

data class CounterValueViewModel (

    @Json(name = "targetsValues")
    var targetsValues: CounterValueTargetsModel? = null,

    /* Значение счетчика. */
    @Json(name = "value")
    var `value`: kotlin.Double? = null,

    /* Идентификаторы значений счетчика. */
    @Json(name = "hashes")
    var hashes: kotlin.collections.MutableList<kotlin.String>? = null,

    /* Дата обновления счетчика. */
    @Json(name = "updateDate")
    var updateDate: java.time.OffsetDateTime? = null

)

