/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package loymax.sdk.models


import com.squareup.moshi.Json

/**
 * Модель представления страны.
 *
 * @param id Id страны.
 * @param name Наименование страны.
 * @param code Код страны (по стандарту ISO-3166 alpha-2).
 */

data class CountryViewModel (

    /* Id страны. */
    @Json(name = "id")
    var id: kotlin.Int? = null,

    /* Наименование страны. */
    @Json(name = "name")
    var name: kotlin.String? = null,

    /* Код страны (по стандарту ISO-3166 alpha-2). */
    @Json(name = "code")
    var code: kotlin.String? = null

)

