/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package loymax.sdk.models

import loymax.sdk.models.CounterTarget

import com.squareup.moshi.Json

/**
 * Параметр счетчика.
 *
 * @param `value` 
 */

data class CounterTargetDto (

    @Json(name = "value")
    var `value`: CounterTarget? = null

)

