/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package loymax.sdk.models


import com.squareup.moshi.Json

/**
 * 
 *
 * Values: EVENT_DATE_TIME,SOURCE_DATE_TIME,PERSON,CARD,PARTNER,DEVICE,MERCHANT,O_AUTH_IDENTIFIER_INFO,O_AUTH_ACTIVITY_TYPE,O_AUTH_OBJECT_ID,O_AUTH_GROUP_ID,ACCOUNT_GROUP,REFUNDED_PURCHASE,REFERRAL,PURCHASE,LEGAL,EVENT_DAY,EVENT_MONTH,EVENT_YEAR,WEEK,GOOD,OFFER
 */

enum class CounterTarget(val value: kotlin.String) {

    @Json(name = "EventDateTime")
    EVENT_DATE_TIME("EventDateTime"),

    @Json(name = "SourceDateTime")
    SOURCE_DATE_TIME("SourceDateTime"),

    @Json(name = "Person")
    PERSON("Person"),

    @Json(name = "Card")
    CARD("Card"),

    @Json(name = "Partner")
    PARTNER("Partner"),

    @Json(name = "Device")
    DEVICE("Device"),

    @Json(name = "Merchant")
    MERCHANT("Merchant"),

    @Json(name = "OAuthIdentifierInfo")
    O_AUTH_IDENTIFIER_INFO("OAuthIdentifierInfo"),

    @Json(name = "OAuthActivityType")
    O_AUTH_ACTIVITY_TYPE("OAuthActivityType"),

    @Json(name = "OAuthObjectId")
    O_AUTH_OBJECT_ID("OAuthObjectId"),

    @Json(name = "OAuthGroupId")
    O_AUTH_GROUP_ID("OAuthGroupId"),

    @Json(name = "AccountGroup")
    ACCOUNT_GROUP("AccountGroup"),

    @Json(name = "RefundedPurchase")
    REFUNDED_PURCHASE("RefundedPurchase"),

    @Json(name = "Referral")
    REFERRAL("Referral"),

    @Json(name = "Purchase")
    PURCHASE("Purchase"),

    @Json(name = "Legal")
    LEGAL("Legal"),

    @Json(name = "EventDay")
    EVENT_DAY("EventDay"),

    @Json(name = "EventMonth")
    EVENT_MONTH("EventMonth"),

    @Json(name = "EventYear")
    EVENT_YEAR("EventYear"),

    @Json(name = "Week")
    WEEK("Week"),

    @Json(name = "Good")
    GOOD("Good"),

    @Json(name = "Offer")
    OFFER("Offer");

    /**
     * Override toString() to avoid using the enum variable name as the value, and instead use
     * the actual value defined in the API spec file.
     *
     * This solves a problem when the variable name and its value are different, and ensures that
     * the client sends the correct enum values to the server always.
     */
    override fun toString(): String = value

    companion object {
        /**
         * Converts the provided [data] to a [String] on success, null otherwise.
         */
        fun encode(data: kotlin.Any?): kotlin.String? = if (data is CounterTarget) "$data" else null

        /**
         * Returns a valid [CounterTarget] for [data], null otherwise.
         */
        fun decode(data: kotlin.Any?): CounterTarget? = data?.let {
          val normalizedData = "$it".lowercase()
          values().firstOrNull { value ->
            it == value || normalizedData == "$value".lowercase()
          }
        }
    }
}

