/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package loymax.sdk.models


import com.squareup.moshi.Json

/**
 * Действие акции \"Выдача купона\".
 *
 * @param order Порядковый номер действия в цепочке.
 * @param id Id действия в цепочке.
 * @param couponEmissionId Идентификатор выпуска.
 * @param issueCount Количество выдаваемых купонов.
 */

data class CouponIssueActionDto (

    /* Порядковый номер действия в цепочке. */
    @Json(name = "order")
    var order: kotlin.Int? = null,

    /* Id действия в цепочке. */
    @Json(name = "id")
    var id: kotlin.String? = null,

    /* Идентификатор выпуска. */
    @Json(name = "couponEmissionId")
    var couponEmissionId: kotlin.Int? = null,

    /* Количество выдаваемых купонов. */
    @Json(name = "issueCount")
    var issueCount: kotlin.Int? = null

)

