/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package loymax.sdk.models

import loymax.sdk.models.FileViewModel
import loymax.sdk.models.KeyValuePairOfCouponStateAndInt32
import loymax.sdk.models.MoneyViewModel

import com.squareup.moshi.Json

/**
 * ViewModel выпуска купонов.
 *
 * @param id Идентификатор.
 * @param title Название выпуска.
 * @param creationDate Время создания.
 * @param startDate Время старта.
 * @param expiresDate Время когдя истекает купон.
 * @param price 
 * @param counts Количество купонов в эмиссии в разрезе состояний.
 * @param shortDescription Короткое описание.
 * @param description Описание.
 * @param imageFile 
 */

data class CouponEmissionViewModel (

    /* Идентификатор. */
    @Json(name = "id")
    var id: kotlin.Int? = null,

    /* Название выпуска. */
    @Json(name = "title")
    var title: kotlin.String? = null,

    /* Время создания. */
    @Json(name = "creationDate")
    var creationDate: java.time.OffsetDateTime? = null,

    /* Время старта. */
    @Json(name = "startDate")
    var startDate: java.time.OffsetDateTime? = null,

    /* Время когдя истекает купон. */
    @Json(name = "expiresDate")
    var expiresDate: java.time.OffsetDateTime? = null,

    @Json(name = "price")
    var price: MoneyViewModel? = null,

    /* Количество купонов в эмиссии в разрезе состояний. */
    @Json(name = "counts")
    var counts: kotlin.collections.MutableList<KeyValuePairOfCouponStateAndInt32>? = null,

    /* Короткое описание. */
    @Json(name = "shortDescription")
    var shortDescription: kotlin.String? = null,

    /* Описание. */
    @Json(name = "description")
    var description: kotlin.String? = null,

    @Json(name = "imageFile")
    var imageFile: FileViewModel? = null

)

