/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package loymax.sdk.models

import loymax.sdk.models.CouponState
import loymax.sdk.models.FileViewModel

import com.squareup.moshi.Json

/**
 * ViewModel для купона.
 *
 * @param id Внутренний идентификатор купона.
 * @param code Код.
 * @param qrContent QR-код.
 * @param createDate Дата создания.
 * @param updateDate Дата обновления.
 * @param activationDate Дата активации.
 * @param expiryDate Дата сгорания.
 * @param couponState 
 * @param emissionTitle Название выпуска купонов.
 * @param emissionId Внутренний идентификатор выпуска купонов.
 * @param emissionUid Внешний идентификатор выпуска купонов.
 * @param shortDescription Краткое описание.
 * @param description Описание.
 * @param imageFile 
 */

data class CouponViewModel (

    /* Внутренний идентификатор купона. */
    @Json(name = "id")
    var id: kotlin.Int? = null,

    /* Код. */
    @Json(name = "code")
    var code: kotlin.String? = null,

    /* QR-код. */
    @Json(name = "qrContent")
    var qrContent: kotlin.String? = null,

    /* Дата создания. */
    @Json(name = "createDate")
    var createDate: java.time.OffsetDateTime? = null,

    /* Дата обновления. */
    @Json(name = "updateDate")
    var updateDate: java.time.OffsetDateTime? = null,

    /* Дата активации. */
    @Json(name = "activationDate")
    var activationDate: java.time.OffsetDateTime? = null,

    /* Дата сгорания. */
    @Json(name = "expiryDate")
    var expiryDate: java.time.OffsetDateTime? = null,

    @Json(name = "couponState")
    var couponState: CouponState? = null,

    /* Название выпуска купонов. */
    @Json(name = "emissionTitle")
    var emissionTitle: kotlin.String? = null,

    /* Внутренний идентификатор выпуска купонов. */
    @Json(name = "emissionId")
    var emissionId: kotlin.Int? = null,

    /* Внешний идентификатор выпуска купонов. */
    @Json(name = "emissionUid")
    var emissionUid: java.util.UUID? = null,

    /* Краткое описание. */
    @Json(name = "shortDescription")
    var shortDescription: kotlin.String? = null,

    /* Описание. */
    @Json(name = "description")
    var description: kotlin.String? = null,

    @Json(name = "imageFile")
    var imageFile: FileViewModel? = null

)

