/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package loymax.sdk.models


import com.squareup.moshi.Json

/**
 * Модель для создания акции.
 *
 * @param name Название акции.
 * @param dateFrom Дата начала действия акции.
 * @param dateTo Дата окончания действия акции.
 * @param partnerId Внутренний идентификатор Партнера.
 * @param description Описание акции.
 * @param isSum Признак суммируемости акции с другими (true — суммируется, false — не суммируется).
 * @param priority Приоритет акции.
 * @param loyaltyProgramId Внутренний идентификатор Программы лояльности.
 */

data class CreateOfferModel (

    /* Название акции. */
    @Json(name = "name")
    var name: kotlin.String? = null,

    /* Дата начала действия акции. */
    @Json(name = "dateFrom")
    var dateFrom: java.time.OffsetDateTime? = null,

    /* Дата окончания действия акции. */
    @Json(name = "dateTo")
    var dateTo: java.time.OffsetDateTime? = null,

    /* Внутренний идентификатор Партнера. */
    @Json(name = "partnerId")
    var partnerId: kotlin.Int? = null,

    /* Описание акции. */
    @Json(name = "description")
    var description: kotlin.String? = null,

    /* Признак суммируемости акции с другими (true — суммируется, false — не суммируется). */
    @Json(name = "isSum")
    var isSum: kotlin.Boolean? = null,

    /* Приоритет акции. */
    @Json(name = "priority")
    var priority: kotlin.Int? = null,

    /* Внутренний идентификатор Программы лояльности. */
    @Json(name = "loyaltyProgramId")
    var loyaltyProgramId: kotlin.Int? = null

)

