/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package loymax.sdk.models

import loymax.sdk.models.OfferEventInfoModel

import com.squareup.moshi.Json

/**
 * Модель для создания цепочки событий.
 *
 * @param eventInfo 
 * @param name Название цепочки.
 */

data class CreateOfferActionChainModel (

    @Json(name = "eventInfo")
    var eventInfo: OfferEventInfoModel? = null,

    /* Название цепочки. */
    @Json(name = "name")
    var name: kotlin.String? = null

)

