/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package loymax.sdk.models

import loymax.sdk.models.IdentifierType

import com.squareup.moshi.Json

/**
 * 
 *
 * @param filterTree 
 */

data class CustomerIdentificationTreeModel (

    @Json(name = "filterTree")
    var filterTree: kotlin.collections.MutableList<kotlin.collections.MutableList<IdentifierType>>? = null

)

