/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package loymax.sdk.models


import com.squareup.moshi.Json

/**
 * Модель для удаления действия.
 *
 * @param offerId Id акции.
 * @param actionChainId Id цепочки действий.
 * @param actionId Id действия.
 */

data class DeleteActionModel (

    /* Id акции. */
    @Json(name = "offerId")
    var offerId: kotlin.Int? = null,

    /* Id цепочки действий. */
    @Json(name = "actionChainId")
    var actionChainId: kotlin.Int? = null,

    /* Id действия. */
    @Json(name = "actionId")
    var actionId: kotlin.Int? = null

)

