/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package loymax.sdk.models

import loymax.sdk.models.BonusOperationPurchaseViewModel
import loymax.sdk.models.OfferInfoShortViewModel

import com.squareup.moshi.Json

/**
 * Детальная модель изменения бонусного счета.
 *
 * @param amount Сумма со знаком.
 * @param date Дата.
 * @param balance Баланс счета на момент изменения.
 * @param sourceOperationDate Время исходной операции по счету в часовом поясе владельца счета.
 * @param sourceOperationDescription Описание исходной операции по счету.
 * @param purchase 
 * @param offer 
 */

data class DetailedAccountChangeViewModel (

    /* Сумма со знаком. */
    @Json(name = "amount")
    var amount: kotlin.Double? = null,

    /* Дата. */
    @Json(name = "date")
    var date: java.time.OffsetDateTime? = null,

    /* Баланс счета на момент изменения. */
    @Json(name = "balance")
    var balance: kotlin.Double? = null,

    /* Время исходной операции по счету в часовом поясе владельца счета. */
    @Json(name = "sourceOperationDate")
    var sourceOperationDate: java.time.OffsetDateTime? = null,

    /* Описание исходной операции по счету. */
    @Json(name = "sourceOperationDescription")
    var sourceOperationDescription: kotlin.String? = null,

    @Json(name = "purchase")
    var purchase: BonusOperationPurchaseViewModel? = null,

    @Json(name = "offer")
    var offer: OfferInfoShortViewModel? = null

)

