/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package loymax.sdk.models

import loymax.sdk.models.DeviceEmulationIdentifierViewModel

import com.squareup.moshi.Json

/**
 * Модель добавления оплаты.
 *
 * @param identifier 
 * @param amount Сумма.
 * @param pin Код подтверждения.
 */

data class DeviceEmulationAddBonusPaymentModel (

    @Json(name = "identifier")
    var identifier: DeviceEmulationIdentifierViewModel? = null,

    /* Сумма. */
    @Json(name = "amount")
    var amount: kotlin.Double? = null,

    /* Код подтверждения. */
    @Json(name = "pin")
    var pin: kotlin.String? = null

)

