/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package loymax.sdk.models


import com.squareup.moshi.Json

/**
 * Модель касс для привязки к OAuth-приложениям.
 *
 * @param from Порядковый номер начального элемента выборки.
 * @param count Количество возвращаемых элементов выборки.
 * @param logicalId Логическое имя кассы.
 * @param oAuthApplicationId Внутренний идентификатор OAuth-приложения.
 */

data class DevicesForApplicationFilter (

    /* Порядковый номер начального элемента выборки. */
    @Json(name = "from")
    var from: kotlin.Int? = null,

    /* Количество возвращаемых элементов выборки. */
    @Json(name = "count")
    var count: kotlin.Int? = null,

    /* Логическое имя кассы. */
    @Json(name = "logicalId")
    var logicalId: kotlin.String? = null,

    /* Внутренний идентификатор OAuth-приложения. */
    @Json(name = "oAuthApplicationId")
    var oAuthApplicationId: kotlin.Int? = null

)

