/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package loymax.sdk.models


import com.squareup.moshi.Json

/**
 * Тип авторизации (none — не установлен, LastFourNumbers — последние четыре цифры, PINCode — ПИН-код).
 *
 * Values: NONE,LAST_FOUR_NUMBERS,PIN_CODE
 */

enum class DeviceOperationAuthType(val value: kotlin.String) {

    @Json(name = "None")
    NONE("None"),

    @Json(name = "LastFourNumbers")
    LAST_FOUR_NUMBERS("LastFourNumbers"),

    @Json(name = "PINCode")
    PIN_CODE("PINCode");

    /**
     * Override toString() to avoid using the enum variable name as the value, and instead use
     * the actual value defined in the API spec file.
     *
     * This solves a problem when the variable name and its value are different, and ensures that
     * the client sends the correct enum values to the server always.
     */
    override fun toString(): String = value

    companion object {
        /**
         * Converts the provided [data] to a [String] on success, null otherwise.
         */
        fun encode(data: kotlin.Any?): kotlin.String? = if (data is DeviceOperationAuthType) "$data" else null

        /**
         * Returns a valid [DeviceOperationAuthType] for [data], null otherwise.
         */
        fun decode(data: kotlin.Any?): DeviceOperationAuthType? = data?.let {
          val normalizedData = "$it".lowercase()
          values().firstOrNull { value ->
            it == value || normalizedData == "$value".lowercase()
          }
        }
    }
}

