/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package loymax.sdk.models

import loymax.sdk.models.DeviceCapabilityViewModel

import com.squareup.moshi.Json

/**
 * Список возможностей кассы для обновления.
 *
 * @param capabilities Коллекция новых значений.
 */

data class DeviceCapabilityListViewModel (

    /* Коллекция новых значений. */
    @Json(name = "capabilities")
    var capabilities: kotlin.collections.MutableList<DeviceCapabilityViewModel>? = null

)

