/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package loymax.sdk.models


import com.squareup.moshi.Json

/**
 * Информация об устройстве.
 *
 * @param isPushable Устройству можно отправлять пуши.
 */

data class DeviceInfoModel (

    /* Устройству можно отправлять пуши. */
    @Json(name = "isPushable")
    var isPushable: kotlin.Boolean? = null

)

