/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package loymax.sdk.models

import loymax.sdk.models.DeviceEmulationIdentifierViewModel

import com.squareup.moshi.Json

/**
 * Модель оплаты для тестовой кассы.
 *
 * @param paymentType Логическое имя типа оплаты.
 * @param paymentName Название типа оплаты.
 * @param amount Сумма.
 * @param info Информация.
 * @param identifier 
 */

data class DeviceEmulationPaymentViewModel (

    /* Логическое имя типа оплаты. */
    @Json(name = "paymentType")
    var paymentType: kotlin.String? = null,

    /* Название типа оплаты. */
    @Json(name = "paymentName")
    var paymentName: kotlin.String? = null,

    /* Сумма. */
    @Json(name = "amount")
    var amount: kotlin.Double? = null,

    /* Информация. */
    @Json(name = "info")
    var info: kotlin.String? = null,

    @Json(name = "identifier")
    var identifier: DeviceEmulationIdentifierViewModel? = null

)

