/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package loymax.sdk.models


import com.squareup.moshi.Json

/**
 * Краткая модель представления кассы.
 *
 * @param id Id девайса.
 * @param code Код.
 * @param uid Uid.
 * @param logicalId Код.
 * @param name Название устройства.
 * @param isDeleted Статус устройства (true — архивный, false — неархивный).
 * @param partnerId Внутренний идентификатор Партнера.
 * @param merchantId Внутренний идентификатор магазина.
 */

data class DeviceBriefViewModel (

    /* Id девайса. */
    @Json(name = "id")
    var id: kotlin.Int? = null,

    /* Код. */
    @Json(name = "code")
    var code: kotlin.String? = null,

    /* Uid. */
    @Json(name = "uid")
    var uid: java.util.UUID? = null,

    /* Код. */
    @Json(name = "logicalId")
    var logicalId: kotlin.String? = null,

    /* Название устройства. */
    @Json(name = "name")
    var name: kotlin.String? = null,

    /* Статус устройства (true — архивный, false — неархивный). */
    @Json(name = "isDeleted")
    var isDeleted: kotlin.Boolean? = null,

    /* Внутренний идентификатор Партнера. */
    @Json(name = "partnerId")
    var partnerId: kotlin.Int? = null,

    /* Внутренний идентификатор магазина. */
    @Json(name = "merchantId")
    var merchantId: kotlin.Int? = null

)

