/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package loymax.sdk.models

import loymax.sdk.models.ArchivedState
import loymax.sdk.models.EmissionTypeEnum

import com.squareup.moshi.Json

/**
 * Фильтр для шаблонов для генерации номеров выпусков.
 *
 * @param from Начало выборки.
 * @param count Количество.
 * @param emissionType 
 * @param textSubStr Подстрока текстового описания шаблона.
 * @param showMode 
 */

data class EmissionNumberTemplateFilter (

    /* Начало выборки. */
    @Json(name = "from")
    var from: kotlin.Int? = null,

    /* Количество. */
    @Json(name = "count")
    var count: kotlin.Int? = null,

    @Json(name = "emissionType")
    var emissionType: EmissionTypeEnum? = null,

    /* Подстрока текстового описания шаблона. */
    @Json(name = "textSubStr")
    var textSubStr: kotlin.String? = null,

    @Json(name = "showMode")
    var showMode: ArchivedState? = null

)

