/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package loymax.sdk.models


import com.squareup.moshi.Json

/**
 * 
 *
 * Values: OFFERS,MAILINGS,TARGET_GROUPS,GOODS_GROUPS,MARKETING_CAMPAIGNS
 */

enum class EntityType(val value: kotlin.String) {

    @Json(name = "Offers")
    OFFERS("Offers"),

    @Json(name = "Mailings")
    MAILINGS("Mailings"),

    @Json(name = "TargetGroups")
    TARGET_GROUPS("TargetGroups"),

    @Json(name = "GoodsGroups")
    GOODS_GROUPS("GoodsGroups"),

    @Json(name = "MarketingCampaigns")
    MARKETING_CAMPAIGNS("MarketingCampaigns");

    /**
     * Override toString() to avoid using the enum variable name as the value, and instead use
     * the actual value defined in the API spec file.
     *
     * This solves a problem when the variable name and its value are different, and ensures that
     * the client sends the correct enum values to the server always.
     */
    override fun toString(): String = value

    companion object {
        /**
         * Converts the provided [data] to a [String] on success, null otherwise.
         */
        fun encode(data: kotlin.Any?): kotlin.String? = if (data is EntityType) "$data" else null

        /**
         * Returns a valid [EntityType] for [data], null otherwise.
         */
        fun decode(data: kotlin.Any?): EntityType? = data?.let {
          val normalizedData = "$it".lowercase()
          values().firstOrNull { value ->
            it == value || normalizedData == "$value".lowercase()
          }
        }
    }
}

