/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package loymax.sdk.models


import com.squareup.moshi.Json

/**
 * Фильтр плагинов.
 *
 * @param nameSearchedText Текст поиска в имени.
 * @param classNameSearchedText Текст поиска в имени класса.
 * @param isDisabled Состояние.
 */

data class ExtensionFilter (

    /* Текст поиска в имени. */
    @Json(name = "nameSearchedText")
    var nameSearchedText: kotlin.String? = null,

    /* Текст поиска в имени класса. */
    @Json(name = "classNameSearchedText")
    var classNameSearchedText: kotlin.String? = null,

    /* Состояние. */
    @Json(name = "isDisabled")
    var isDisabled: kotlin.Boolean? = null

)

