/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package loymax.sdk.models

import loymax.sdk.models.ActionTypeViewModel
import loymax.sdk.models.FavoriteGoodsChangeType

import com.squareup.moshi.Json

/**
 * View модель дейтвия сообщение на чек.
 *
 * @param actionId Id действия. Если указан, редактируется действие, иначе создается новое.
 * @param actionType 
 * @param order Порядок действия.
 * @param changeType 
 * @param `value` Значение.
 * @param clearCells Флаг очистки ячеек.
 * @param attributeId Идентификатор атрибута персонального предложения.
 */

data class FavoriteGoodsActionViewModel (

    /* Id действия. Если указан, редактируется действие, иначе создается новое. */
    @Json(name = "actionId")
    var actionId: kotlin.Int? = null,

    @Json(name = "actionType")
    var actionType: ActionTypeViewModel? = null,

    /* Порядок действия. */
    @Json(name = "order")
    var order: kotlin.Int? = null,

    @Json(name = "changeType")
    var changeType: FavoriteGoodsChangeType? = null,

    /* Значение. */
    @Json(name = "value")
    var `value`: kotlin.Int? = null,

    /* Флаг очистки ячеек. */
    @Json(name = "clearCells")
    var clearCells: kotlin.Boolean? = null,

    /* Идентификатор атрибута персонального предложения. */
    @Json(name = "attributeId")
    var attributeId: kotlin.Int? = null

)

