/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package loymax.sdk.models


import com.squareup.moshi.Json

/**
 * Фильтр для списка файлов.
 *
 * @param from Порядковый номер начального элемента выборки.
 * @param count Количество возвращаемых элементов выборки.
 * @param fileName Название файла.
 * @param fileGuid Внешний идентификатор файла.
 */

data class FileFilter (

    /* Порядковый номер начального элемента выборки. */
    @Json(name = "from")
    var from: kotlin.Int? = null,

    /* Количество возвращаемых элементов выборки. */
    @Json(name = "count")
    var count: kotlin.Int? = null,

    /* Название файла. */
    @Json(name = "fileName")
    var fileName: kotlin.String? = null,

    /* Внешний идентификатор файла. */
    @Json(name = "fileGuid")
    var fileGuid: java.util.UUID? = null

)

