/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package loymax.sdk.models


import com.squareup.moshi.Json

/**
 * Операция для фильтра.
 *
 * Values: more,less,equals,between,moreOrEqual,lessOrEqual,betweenLessEqual,betweenMoreEqual,betweenEqual,each,isInList
 */

enum class FilterOperation(val value: kotlin.String) {

    @Json(name = "More")
    more("More"),

    @Json(name = "Less")
    less("Less"),

    @Json(name = "Equals")
    equals("Equals"),

    @Json(name = "Between")
    between("Between"),

    @Json(name = "MoreOrEqual")
    moreOrEqual("MoreOrEqual"),

    @Json(name = "LessOrEqual")
    lessOrEqual("LessOrEqual"),

    @Json(name = "BetweenLessEqual")
    betweenLessEqual("BetweenLessEqual"),

    @Json(name = "BetweenMoreEqual")
    betweenMoreEqual("BetweenMoreEqual"),

    @Json(name = "BetweenEqual")
    betweenEqual("BetweenEqual"),

    @Json(name = "Each")
    each("Each"),

    @Json(name = "IsInList")
    isInList("IsInList");

    /**
     * Override toString() to avoid using the enum variable name as the value, and instead use
     * the actual value defined in the API spec file.
     *
     * This solves a problem when the variable name and its value are different, and ensures that
     * the client sends the correct enum values to the server always.
     */
    override fun toString(): String = value

    companion object {
        /**
         * Converts the provided [data] to a [String] on success, null otherwise.
         */
        fun encode(data: kotlin.Any?): kotlin.String? = if (data is FilterOperation) "$data" else null

        /**
         * Returns a valid [FilterOperation] for [data], null otherwise.
         */
        fun decode(data: kotlin.Any?): FilterOperation? = data?.let {
          val normalizedData = "$it".lowercase()
          values().firstOrNull { value ->
            it == value || normalizedData == "$value".lowercase()
          }
        }
    }
}

