/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package loymax.sdk.models

import loymax.sdk.models.TimeIntervalRoundType
import loymax.sdk.models.TimeUnit

import com.squareup.moshi.Json

/**
 * View-модель для плавающего периода в фильтре по покупкам.
 *
 * @param dateIntervalDuration Продолжительность плавающего периода для даты покупки.
 * @param dateIntervalTimeUnit 
 * @param dateIntervalRoundType 
 */

data class FloatingPurchaseFilterPeriodViewModel (

    /* Продолжительность плавающего периода для даты покупки. */
    @Json(name = "dateIntervalDuration")
    var dateIntervalDuration: kotlin.Int? = null,

    @Json(name = "dateIntervalTimeUnit")
    var dateIntervalTimeUnit: TimeUnit? = null,

    @Json(name = "dateIntervalRoundType")
    var dateIntervalRoundType: TimeIntervalRoundType? = null

)

