/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package loymax.sdk.models


import com.squareup.moshi.Json

/**
 * Полная модель группы товаров.
 *
 * @param id Id группы товаров.
 * @param name Имя группы товаров.
 * @param includeItems Включаемые товары.
 * @param excludeItems Исключаемые товары.
 * @param partnerId Id партнёра.
 */

data class FullGoodsGroupDto (

    /* Id группы товаров. */
    @Json(name = "id")
    var id: java.util.UUID? = null,

    /* Имя группы товаров. */
    @Json(name = "name")
    var name: kotlin.String? = null,

    /* Включаемые товары. */
    @Json(name = "includeItems")
    var includeItems: kotlin.collections.MutableList<kotlin.String>? = null,

    /* Исключаемые товары. */
    @Json(name = "excludeItems")
    var excludeItems: kotlin.collections.MutableList<kotlin.String>? = null,

    /* Id партнёра. */
    @Json(name = "partnerId")
    var partnerId: java.util.UUID? = null

)

