/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package loymax.sdk.models


import com.squareup.moshi.Json

/**
 * 
 *
 * @param id 
 * @param name 
 * @param code 
 * @param queueRoute 
 * @param config 
 * @param providerId 
 * @param enabled 
 */

data class GatewayModel (

    @Json(name = "id")
    var id: kotlin.Int? = null,

    @Json(name = "name")
    var name: kotlin.String? = null,

    @Json(name = "code")
    var code: kotlin.String? = null,

    @Json(name = "queueRoute")
    var queueRoute: kotlin.String? = null,

    @Json(name = "config")
    var config: kotlin.String? = null,

    @Json(name = "providerId")
    var providerId: kotlin.Int? = null,

    @Json(name = "enabled")
    var enabled: kotlin.Boolean? = null

)

