/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package loymax.sdk.models

import loymax.sdk.models.ViewMode

import com.squareup.moshi.Json

/**
 * Модель фильтра для получения модели одной акции.
 *
 * @param offerId Id акции.
 * @param mode 
 */

data class GetOfferFilter (

    /* Id акции. */
    @Json(name = "offerId")
    var offerId: kotlin.Int? = null,

    @Json(name = "mode")
    var mode: ViewMode? = null

)

