/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package loymax.sdk.models

import loymax.sdk.models.ItemDataModel

import com.squareup.moshi.Json

/**
 * Модель сертификата в ответе.
 *
 * @param positionId Номер позиции.
 * @param `data` Дополнительная информация.
 */

data class GiftCertificateModel (

    /* Номер позиции. */
    @Json(name = "positionId")
    var positionId: kotlin.String? = null,

    /* Дополнительная информация. */
    @Json(name = "data")
    var `data`: kotlin.collections.MutableList<ItemDataModel>? = null

)

