/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package loymax.sdk.models

import loymax.sdk.models.GoodsSetDto

import com.squareup.moshi.Json

/**
 * Группа товаров.
 *
 * @param id Идентификатор группы товаров.
 * @param name Название группы товаров.
 * @param partnerId Идентификатор партнера.
 * @param isFixed Фиксирована ли группа товаров.
 * @param includingSets Включающие наборы.
 * @param excludingSets Исключающие наборы.
 */

data class GoodsGroupDto (

    /* Идентификатор группы товаров. */
    @Json(name = "id")
    var id: java.util.UUID? = null,

    /* Название группы товаров. */
    @Json(name = "name")
    var name: kotlin.String? = null,

    /* Идентификатор партнера. */
    @Json(name = "partnerId")
    var partnerId: java.util.UUID? = null,

    /* Фиксирована ли группа товаров. */
    @Json(name = "isFixed")
    var isFixed: kotlin.Boolean? = null,

    /* Включающие наборы. */
    @Json(name = "includingSets")
    var includingSets: kotlin.collections.MutableList<GoodsSetDto>? = null,

    /* Исключающие наборы. */
    @Json(name = "excludingSets")
    var excludingSets: kotlin.collections.MutableList<GoodsSetDto>? = null

)

