/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package loymax.sdk.models

import loymax.sdk.models.GoodsCalculationDiscountResponseModel

import com.squareup.moshi.Json

/**
 * Модель для результатов обсчёта товаров.
 *
 * @param goodsCalculationDiscountResult Преференции по акциям.
 * @param sumDiscount Общая сумма скидок.
 * @param resultAmount Стоимость с учетом скидок.
 */

data class GoodsCalculationDiscountsCollectionResponseModel (

    /* Преференции по акциям. */
    @Json(name = "goodsCalculationDiscountResult")
    var goodsCalculationDiscountResult: kotlin.collections.MutableList<GoodsCalculationDiscountResponseModel>? = null,

    /* Общая сумма скидок. */
    @Json(name = "sumDiscount")
    var sumDiscount: kotlin.Double? = null,

    /* Стоимость с учетом скидок. */
    @Json(name = "resultAmount")
    var resultAmount: kotlin.Double? = null

)

