/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package loymax.sdk.models

import loymax.sdk.models.CheckState

import com.squareup.moshi.Json

/**
 * Подкаталог каталога в группе товаров.
 *
 * @param id Идентификатор подкаталога.
 * @param state 
 */

data class GoodsSetCatalogItem (

    /* Идентификатор подкаталога. */
    @Json(name = "id")
    var id: kotlin.Int? = null,

    @Json(name = "state")
    var state: CheckState? = null

)

