/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package loymax.sdk.models

import loymax.sdk.models.GoodsSetType

import com.squareup.moshi.Json

/**
 * Модель набора товаров.
 *
 * @param name Название.
 * @param type 
 */

data class GoodsSetModel (

    /* Название. */
    @Json(name = "name")
    var name: kotlin.String? = null,

    @Json(name = "type")
    var type: GoodsSetType? = null

)

