/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package loymax.sdk.models


import com.squareup.moshi.Json

/**
 * Ошибка при импорте групп товаров.
 *
 * @param goodsGroupId Идентификатор группы товаров.
 * @param errorCode Код ошибки.
 * @param errorMessage Описание ошибки.
 */

data class GoodsGroupsImportError (

    /* Идентификатор группы товаров. */
    @Json(name = "goodsGroupId")
    var goodsGroupId: java.util.UUID? = null,

    /* Код ошибки. */
    @Json(name = "errorCode")
    var errorCode: kotlin.Int? = null,

    /* Описание ошибки. */
    @Json(name = "errorMessage")
    var errorMessage: kotlin.String? = null

)

