/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package loymax.sdk.models

import loymax.sdk.models.CheckState

import com.squareup.moshi.Json

/**
 * View модель для элемента каталога товаров.
 *
 * @param name Название.
 * @param id Id.
 * @param goodsCode Код товара.
 * @param parentID Id родительского каталога.
 * @param isEnabled Включено или нет.
 * @param checkState 
 * @param partnerId Идентификатор партнера.
 * @param catalogId Идентификатор каталога.
 */

data class GoodsCatalogBaseViewModel (

    /* Название. */
    @Json(name = "name")
    var name: kotlin.String? = null,

    /* Id. */
    @Json(name = "id")
    var id: kotlin.Int? = null,

    /* Код товара. */
    @Json(name = "goodsCode")
    var goodsCode: kotlin.String? = null,

    /* Id родительского каталога. */
    @Json(name = "parentID")
    var parentID: kotlin.Int? = null,

    /* Включено или нет. */
    @Json(name = "isEnabled")
    var isEnabled: kotlin.Boolean? = null,

    @Json(name = "checkState")
    var checkState: CheckState? = null,

    /* Идентификатор партнера. */
    @Json(name = "partnerId")
    var partnerId: kotlin.String? = null,

    /* Идентификатор каталога. */
    @Json(name = "catalogId")
    var catalogId: kotlin.Int? = null

)

