/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package loymax.sdk.models

import loymax.sdk.models.FileViewModel

import com.squareup.moshi.Json

/**
 * Расширение модели мультемедийного атрибута.
 *
 * @param `value` Значение.
 * @param attributeId Id атрибута.
 * @param attributeLogicalName Логическое имя атрибута.
 * @param attributeName Имя атрибута.
 * @param isRelated Значение атрибута получено из связанной сущности.
 * @param file 
 */

data class GuidAttributeValueViewModel (

    /* Значение. */
    @Json(name = "value")
    var `value`: java.util.UUID? = null,

    /* Id атрибута. */
    @Json(name = "attributeId")
    var attributeId: kotlin.Int? = null,

    /* Логическое имя атрибута. */
    @Json(name = "attributeLogicalName")
    var attributeLogicalName: kotlin.String? = null,

    /* Имя атрибута. */
    @Json(name = "attributeName")
    var attributeName: kotlin.String? = null,

    /* Значение атрибута получено из связанной сущности. */
    @Json(name = "isRelated")
    var isRelated: kotlin.Boolean? = null,

    @Json(name = "file")
    var file: FileViewModel? = null

)

