/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package loymax.sdk.models

import loymax.sdk.models.CreatorModel
import loymax.sdk.models.KeyValuePairOfStringAndString
import loymax.sdk.models.UserViewModel

import com.squareup.moshi.Json

/**
 * View model аудита.
 *
 * @param id Идентификатор.
 * @param creationDate Дата создания.
 * @param owner 
 * @param cardNumber Номер карты.
 * @param auditType Тип аудита.
 * @param additionalInfos Дополнительная информация.
 * @param author 
 */

data class HistoryAuditViewModel (

    /* Идентификатор. */
    @Json(name = "id")
    var id: kotlin.Int? = null,

    /* Дата создания. */
    @Json(name = "creationDate")
    var creationDate: java.time.OffsetDateTime? = null,

    @Json(name = "owner")
    var owner: UserViewModel? = null,

    /* Номер карты. */
    @Json(name = "cardNumber")
    var cardNumber: kotlin.String? = null,

    /* Тип аудита. */
    @Json(name = "auditType")
    var auditType: kotlin.String? = null,

    /* Дополнительная информация. */
    @Json(name = "additionalInfos")
    var additionalInfos: kotlin.collections.MutableList<KeyValuePairOfStringAndString>? = null,

    @Json(name = "author")
    var author: CreatorModel? = null

)

