/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package loymax.sdk.models


import com.squareup.moshi.Json

/**
 * 
 *
 * @param dateFrom 
 * @param dateTo 
 * @param cardNumber 
 * @param auditTypes 
 * @param personId 
 * @param isUser 
 * @param clientAuditsRequired 
 */

data class HistoryAuditFilter (

    @Json(name = "dateFrom")
    var dateFrom: java.time.OffsetDateTime? = null,

    @Json(name = "dateTo")
    var dateTo: java.time.OffsetDateTime? = null,

    @Json(name = "cardNumber")
    var cardNumber: kotlin.String? = null,

    @Json(name = "auditTypes")
    var auditTypes: kotlin.collections.MutableList<kotlin.String>? = null,

    @Json(name = "personId")
    var personId: kotlin.Int? = null,

    @Json(name = "isUser")
    var isUser: kotlin.Boolean? = null,

    @Json(name = "clientAuditsRequired")
    var clientAuditsRequired: kotlin.Boolean? = null

)

