/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package loymax.sdk.models


import com.squareup.moshi.Json

/**
 * Модель для представления времени Часы минуты.
 *
 * @param hour Часы.
 * @param minute Минуты.
 */

data class HourMinuteModelDto (

    /* Часы. */
    @Json(name = "hour")
    var hour: kotlin.Int? = null,

    /* Минуты. */
    @Json(name = "minute")
    var minute: kotlin.Int? = null

)

