/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package loymax.sdk.models

import loymax.sdk.models.FileViewModel

import com.squareup.moshi.Json

/**
 * Модель изображения с файлом.
 *
 * @param id Внутренний идентификатор изображения.
 * @param description Описание изображения.
 * @param file 
 */

data class ImageFileViewModel (

    /* Внутренний идентификатор изображения. */
    @Json(name = "id")
    var id: kotlin.Int? = null,

    /* Описание изображения. */
    @Json(name = "description")
    var description: kotlin.String? = null,

    @Json(name = "file")
    var file: FileViewModel? = null

)

