/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package loymax.sdk.models


import com.squareup.moshi.Json

/**
 * 
 *
 * Values: NUMBER,BAR_CODE,QR_CODE,STRIP1,STRIP2,STRIP3
 */

enum class LabelType(val value: kotlin.String) {

    @Json(name = "Number")
    NUMBER("Number"),

    @Json(name = "BarCode")
    BAR_CODE("BarCode"),

    @Json(name = "QRCode")
    QR_CODE("QRCode"),

    @Json(name = "Strip1")
    STRIP1("Strip1"),

    @Json(name = "Strip2")
    STRIP2("Strip2"),

    @Json(name = "Strip3")
    STRIP3("Strip3");

    /**
     * Override toString() to avoid using the enum variable name as the value, and instead use
     * the actual value defined in the API spec file.
     *
     * This solves a problem when the variable name and its value are different, and ensures that
     * the client sends the correct enum values to the server always.
     */
    override fun toString(): String = value

    companion object {
        /**
         * Converts the provided [data] to a [String] on success, null otherwise.
         */
        fun encode(data: kotlin.Any?): kotlin.String? = if (data is LabelType) "$data" else null

        /**
         * Returns a valid [LabelType] for [data], null otherwise.
         */
        fun decode(data: kotlin.Any?): LabelType? = data?.let {
          val normalizedData = "$it".lowercase()
          values().firstOrNull { value ->
            it == value || normalizedData == "$value".lowercase()
          }
        }
    }
}

