/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package loymax.sdk.models


import com.squareup.moshi.Json

/**
 * 
 *
 * @param minLength 
 * @param maxLength 
 * @param id 
 */

data class LengthAttributeRestriction (

    @Json(name = "minLength")
    var minLength: kotlin.Int? = null,

    @Json(name = "maxLength")
    var maxLength: kotlin.Int? = null,

    @Json(name = "id")
    var id: kotlin.Int? = null

)

