/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package loymax.sdk.models


import com.squareup.moshi.Json

/**
 * Действия при достижении лимита.
 *
 * @param id Идентификатор.
 * @param isArchived В архивном состоянии или нет.
 */

data class LimitActionViewModel (

    /* Идентификатор. */
    @Json(name = "id")
    var id: kotlin.Int? = null,

    /* В архивном состоянии или нет. */
    @Json(name = "isArchived")
    var isArchived: kotlin.Boolean? = null

)

