/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package loymax.sdk.models


import com.squareup.moshi.Json

/**
 * View-модель программы лояльности.
 *
 * @param id Внутренний идентификатор ПЛ.
 * @param name Логическое имя ПЛ.
 */

data class LoyaltyProgramInfoViewModel (

    /* Внутренний идентификатор ПЛ. */
    @Json(name = "id")
    var id: kotlin.Int? = null,

    /* Логическое имя ПЛ. */
    @Json(name = "name")
    var name: kotlin.String? = null

)

