/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package loymax.sdk.models


import com.squareup.moshi.Json

/**
 * Статистика выполнения задачи рассылки.
 *
 * @param personsCount Количество клиентов всего.
 * @param processedNotificationsCount Количество сформированных оповещений.
 * @param processedSmsCount Количество сформированных sms.
 * @param processedMessagesCount Количество сформированных сообщений.
 * @param sentMessagesCount Количество отправленных сообщений.
 * @param deliveryInProcessMessagesCount Количество сообщений, которые находятся на обработке внешним шлюзом.
 * @param deliveredOkMessagesCount Количество успешно доставленных сообщений.
 * @param deliveredFailedMessagesCount Количество сообщений, доставка которых не удалась.
 * @param deliveredReadMessagesCount Количество сообщений, которые прочитаны.
 * @param deliveredUnknownMessagesCount Количество сообщений, у которых неизвестен статус доставки.
 * @param sentMessagesAmount Фактическая стоимость рассылки.
 */

data class MailingTaskStatisticViewModel (

    /* Количество клиентов всего. */
    @Json(name = "personsCount")
    var personsCount: kotlin.Int? = null,

    /* Количество сформированных оповещений. */
    @Json(name = "processedNotificationsCount")
    var processedNotificationsCount: kotlin.Int? = null,

    /* Количество сформированных sms. */
    @Json(name = "processedSmsCount")
    var processedSmsCount: kotlin.Int? = null,

    /* Количество сформированных сообщений. */
    @Json(name = "processedMessagesCount")
    var processedMessagesCount: kotlin.Int? = null,

    /* Количество отправленных сообщений. */
    @Json(name = "sentMessagesCount")
    var sentMessagesCount: kotlin.Int? = null,

    /* Количество сообщений, которые находятся на обработке внешним шлюзом. */
    @Json(name = "deliveryInProcessMessagesCount")
    var deliveryInProcessMessagesCount: kotlin.Int? = null,

    /* Количество успешно доставленных сообщений. */
    @Json(name = "deliveredOkMessagesCount")
    var deliveredOkMessagesCount: kotlin.Int? = null,

    /* Количество сообщений, доставка которых не удалась. */
    @Json(name = "deliveredFailedMessagesCount")
    var deliveredFailedMessagesCount: kotlin.Int? = null,

    /* Количество сообщений, которые прочитаны. */
    @Json(name = "deliveredReadMessagesCount")
    var deliveredReadMessagesCount: kotlin.Int? = null,

    /* Количество сообщений, у которых неизвестен статус доставки. */
    @Json(name = "deliveredUnknownMessagesCount")
    var deliveredUnknownMessagesCount: kotlin.Int? = null,

    /* Фактическая стоимость рассылки. */
    @Json(name = "sentMessagesAmount")
    var sentMessagesAmount: kotlin.Double? = null

)

