/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package loymax.sdk.models


import com.squareup.moshi.Json

/**
 * Модель описывает загружаемые номера телефонов рассылки.
 *
 * @param phonesCsv Строка с номерами телефонов.
 */

data class MailingPhonesModel (

    /* Строка с номерами телефонов. */
    @Json(name = "phonesCsv")
    var phonesCsv: kotlin.String? = null

)

