/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package loymax.sdk.models

import loymax.sdk.models.KeyValuePairOfStringAndString

import com.squareup.moshi.Json

/**
 * Модель пуш сообщения рассылки.
 *
 * @param text Текст.
 * @param additionalInfo Дополнительные параметры.
 * @param header Заголовок.
 * @param imageId Идентификатор изображения.
 * @param shortText Короткий текст.
 */

data class MailingPushMessageViewModel (

    /* Текст. */
    @Json(name = "text")
    var text: kotlin.String? = null,

    /* Дополнительные параметры. */
    @Json(name = "additionalInfo")
    var additionalInfo: kotlin.collections.MutableList<KeyValuePairOfStringAndString>? = null,

    /* Заголовок. */
    @Json(name = "header")
    var header: kotlin.String? = null,

    /* Идентификатор изображения. */
    @Json(name = "imageId")
    var imageId: java.util.UUID? = null,

    /* Короткий текст. */
    @Json(name = "shortText")
    var shortText: kotlin.String? = null

)

