/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package loymax.sdk.models

import loymax.sdk.models.CampaignPermissions
import loymax.sdk.models.PartnerLoyaltyProgramModel
import loymax.sdk.models.PartnerViewModel

import com.squareup.moshi.Json

/**
 * View-модель маркетинговой кампании.
 *
 * @param id Id.
 * @param loyaltyProgram 
 * @param name Название.
 * @param partner 
 * @param beginDate Дата начала.
 * @param endDate Дата окончания.
 * @param isDeleted Значение, определяющее, находится ли кампания в архиве.
 * @param hasMetrics Значение, определяющее, установлены ли для кампании показатели.
 * @param canView 
 * @param canEdit Значение, определяющее, есть ли у пользователя право редактировать кампанию.
 */

data class MarketingCampaignViewModel (

    /* Id. */
    @Json(name = "id")
    var id: kotlin.Int? = null,

    @Json(name = "loyaltyProgram")
    var loyaltyProgram: PartnerLoyaltyProgramModel? = null,

    /* Название. */
    @Json(name = "name")
    var name: kotlin.String? = null,

    @Json(name = "partner")
    var partner: PartnerViewModel? = null,

    /* Дата начала. */
    @Json(name = "beginDate")
    var beginDate: java.time.OffsetDateTime? = null,

    /* Дата окончания. */
    @Json(name = "endDate")
    var endDate: java.time.OffsetDateTime? = null,

    /* Значение, определяющее, находится ли кампания в архиве. */
    @Json(name = "isDeleted")
    var isDeleted: kotlin.Boolean? = null,

    /* Значение, определяющее, установлены ли для кампании показатели. */
    @Json(name = "hasMetrics")
    var hasMetrics: kotlin.Boolean? = null,

    @Json(name = "canView")
    var canView: CampaignPermissions? = null,

    /* Значение, определяющее, есть ли у пользователя право редактировать кампанию. */
    @Json(name = "canEdit")
    var canEdit: kotlin.Boolean? = null

)

