/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package loymax.sdk.models

import loymax.sdk.models.ArchivedState

import com.squareup.moshi.Json

/**
 * Модель для фильтра маркетинговых кампаний.
 *
 * @param fromDate Начало периода.
 * @param toDate Конец периода.
 * @param mode 
 * @param partnerIds Идентификаторы партнеров.
 * @param loyaltyProgramIds Идентификаторы программ лояльности.
 */

data class MarketingCampaignFilter (

    /* Начало периода. */
    @Json(name = "fromDate")
    var fromDate: java.time.OffsetDateTime? = null,

    /* Конец периода. */
    @Json(name = "toDate")
    var toDate: java.time.OffsetDateTime? = null,

    @Json(name = "mode")
    var mode: ArchivedState? = null,

    /* Идентификаторы партнеров. */
    @Json(name = "partnerIds")
    var partnerIds: kotlin.collections.MutableList<kotlin.Int>? = null,

    /* Идентификаторы программ лояльности. */
    @Json(name = "loyaltyProgramIds")
    var loyaltyProgramIds: kotlin.collections.MutableList<kotlin.Int>? = null

)

