/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package loymax.sdk.models


import com.squareup.moshi.Json

/**
 * Краткая информация о магазине.
 *
 * @param id Внутренний идентификатор магазина.
 * @param name Название магазина.
 * @param isDeleted Признак состояния магазина (true - архивный, false - неархивный).
 */

data class MerchantInfoShortViewModel (

    /* Внутренний идентификатор магазина. */
    @Json(name = "id")
    var id: kotlin.Int? = null,

    /* Название магазина. */
    @Json(name = "name")
    var name: kotlin.String? = null,

    /* Признак состояния магазина (true - архивный, false - неархивный). */
    @Json(name = "isDeleted")
    var isDeleted: kotlin.Boolean? = null

)

