/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package loymax.sdk.models


import com.squareup.moshi.Json

/**
 * Тип.
 *
 * Values: CURRENCY,TEXT,ACTION_RESULT_TYPE,COUPONS,MATH,LIMIT_DETAILS
 */

enum class MetavariableTypes(val value: kotlin.String) {

    @Json(name = "Currency")
    CURRENCY("Currency"),

    @Json(name = "Text")
    TEXT("Text"),

    @Json(name = "ActionResultType")
    ACTION_RESULT_TYPE("ActionResultType"),

    @Json(name = "Coupons")
    COUPONS("Coupons"),

    @Json(name = "Math")
    MATH("Math"),

    @Json(name = "LimitDetails")
    LIMIT_DETAILS("LimitDetails");

    /**
     * Override toString() to avoid using the enum variable name as the value, and instead use
     * the actual value defined in the API spec file.
     *
     * This solves a problem when the variable name and its value are different, and ensures that
     * the client sends the correct enum values to the server always.
     */
    override fun toString(): String = value

    companion object {
        /**
         * Converts the provided [data] to a [String] on success, null otherwise.
         */
        fun encode(data: kotlin.Any?): kotlin.String? = if (data is MetavariableTypes) "$data" else null

        /**
         * Returns a valid [MetavariableTypes] for [data], null otherwise.
         */
        fun decode(data: kotlin.Any?): MetavariableTypes? = data?.let {
          val normalizedData = "$it".lowercase()
          values().firstOrNull { value ->
            it == value || normalizedData == "$value".lowercase()
          }
        }
    }
}

