/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package loymax.sdk.models


import com.squareup.moshi.Json

/**
 * Модель представления показателей.
 *
 * @param turnover Товарооборот.
 * @param proceeds Выручка.
 * @param discount Скидка.
 * @param discountPercent Скидка в %.
 * @param accruedSum Начисленно бонусов.
 * @param accruedPercent Начислено бонусов в %.
 * @param paymentBonusesSum Оплата бонусами.
 * @param paymentMoneySum Оплата валютой кассы.
 * @param activeClientsCount Кол-во покупателей.
 * @param chequesCount Кол-во чеков.
 * @param purchasesPerClient Кол-во покупок на 1ого клиента.
 * @param averageChequeSum Средняя сумма чека.
 * @param purchasesSumPerClient Сумма покупок на 1ого клиента.
 * @param discountsSumPerClient Сумма скидок на 1ого клиента.
 * @param cashbacksSumPerClient Сумма начислений на 1ого клиента.
 * @param paymentsSumPerClient Сумма оплаты бонусами на 1ого клиента.
 * @param withdrawsPercentByTurnover Бонусов списано от товарооборота.
 * @param withdrawsPercentByAccruals Кол-во списанных бонусов к кол-ву начисленных.
 */

data class MetricsViewModel (

    /* Товарооборот. */
    @Json(name = "turnover")
    var turnover: kotlin.Double? = null,

    /* Выручка. */
    @Json(name = "proceeds")
    var proceeds: kotlin.Double? = null,

    /* Скидка. */
    @Json(name = "discount")
    var discount: kotlin.Double? = null,

    /* Скидка в %. */
    @Json(name = "discountPercent")
    var discountPercent: kotlin.Double? = null,

    /* Начисленно бонусов. */
    @Json(name = "accruedSum")
    var accruedSum: kotlin.Double? = null,

    /* Начислено бонусов в %. */
    @Json(name = "accruedPercent")
    var accruedPercent: kotlin.Double? = null,

    /* Оплата бонусами. */
    @Json(name = "paymentBonusesSum")
    var paymentBonusesSum: kotlin.Double? = null,

    /* Оплата валютой кассы. */
    @Json(name = "paymentMoneySum")
    var paymentMoneySum: kotlin.Double? = null,

    /* Кол-во покупателей. */
    @Json(name = "activeClientsCount")
    var activeClientsCount: kotlin.Double? = null,

    /* Кол-во чеков. */
    @Json(name = "chequesCount")
    var chequesCount: kotlin.Double? = null,

    /* Кол-во покупок на 1ого клиента. */
    @Json(name = "purchasesPerClient")
    var purchasesPerClient: kotlin.Double? = null,

    /* Средняя сумма чека. */
    @Json(name = "averageChequeSum")
    var averageChequeSum: kotlin.Double? = null,

    /* Сумма покупок на 1ого клиента. */
    @Json(name = "purchasesSumPerClient")
    var purchasesSumPerClient: kotlin.Double? = null,

    /* Сумма скидок на 1ого клиента. */
    @Json(name = "discountsSumPerClient")
    var discountsSumPerClient: kotlin.Double? = null,

    /* Сумма начислений на 1ого клиента. */
    @Json(name = "cashbacksSumPerClient")
    var cashbacksSumPerClient: kotlin.Double? = null,

    /* Сумма оплаты бонусами на 1ого клиента. */
    @Json(name = "paymentsSumPerClient")
    var paymentsSumPerClient: kotlin.Double? = null,

    /* Бонусов списано от товарооборота. */
    @Json(name = "withdrawsPercentByTurnover")
    var withdrawsPercentByTurnover: kotlin.Double? = null,

    /* Кол-во списанных бонусов к кол-ву начисленных. */
    @Json(name = "withdrawsPercentByAccruals")
    var withdrawsPercentByAccruals: kotlin.Double? = null

)

