/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package loymax.sdk.models

import loymax.sdk.models.ActionTypeViewModel

import com.squareup.moshi.Json

/**
 * Модель для редактирования действия \"Установка мин. цены\".
 *
 * @param actionId Id действия. Если указан, редактируется действие, иначе создается новое.
 * @param actionType 
 * @param order Порядок действия.
 * @param percent Процент.
 * @param fixedAmount Фиксированная сумма.
 * @param fixedPrice Фиксированная цена.
 * @param goodsAttributeId Идентификатор атрибута каталога.
 */

data class MinPriceActionViewModel (

    /* Id действия. Если указан, редактируется действие, иначе создается новое. */
    @Json(name = "actionId")
    var actionId: kotlin.Int? = null,

    @Json(name = "actionType")
    var actionType: ActionTypeViewModel? = null,

    /* Порядок действия. */
    @Json(name = "order")
    var order: kotlin.Int? = null,

    /* Процент. */
    @Json(name = "percent")
    var percent: kotlin.Double? = null,

    /* Фиксированная сумма. */
    @Json(name = "fixedAmount")
    var fixedAmount: kotlin.Double? = null,

    /* Фиксированная цена. */
    @Json(name = "fixedPrice")
    var fixedPrice: kotlin.Double? = null,

    /* Идентификатор атрибута каталога. */
    @Json(name = "goodsAttributeId")
    var goodsAttributeId: kotlin.Int? = null

)

