/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package loymax.sdk.models

import loymax.sdk.models.CurrencyInfoModel

import com.squareup.moshi.Json

/**
 * Модель денежных средств.
 *
 * @param amount Сумма.
 * @param currency Валюта.
 * @param currencyInfo 
 */

data class MoneyViewModel (

    /* Сумма. */
    @Json(name = "amount")
    var amount: kotlin.Double? = null,

    /* Валюта. */
    @Json(name = "currency")
    var currency: kotlin.String? = null,

    @Json(name = "currencyInfo")
    var currencyInfo: CurrencyInfoModel? = null

)

