/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package loymax.sdk.models


import com.squareup.moshi.Json

/**
 * 
 *
 * Values: READY_FOR_SEND,SENT,CRITICAL_ERROR,DELIVERY_IN_PROCESS,DELIVERY_OK,DELIVERY_FAILED,DELIVERY_READ,DELIVERY_UNKNOWN,DELETED,NOT_SENT
 */

enum class NotificationMessageState(val value: kotlin.String) {

    @Json(name = "ReadyForSend")
    READY_FOR_SEND("ReadyForSend"),

    @Json(name = "Sent")
    SENT("Sent"),

    @Json(name = "CriticalError")
    CRITICAL_ERROR("CriticalError"),

    @Json(name = "DeliveryInProcess")
    DELIVERY_IN_PROCESS("DeliveryInProcess"),

    @Json(name = "DeliveryOk")
    DELIVERY_OK("DeliveryOk"),

    @Json(name = "DeliveryFailed")
    DELIVERY_FAILED("DeliveryFailed"),

    @Json(name = "DeliveryRead")
    DELIVERY_READ("DeliveryRead"),

    @Json(name = "DeliveryUnknown")
    DELIVERY_UNKNOWN("DeliveryUnknown"),

    @Json(name = "Deleted")
    DELETED("Deleted"),

    @Json(name = "NotSent")
    NOT_SENT("NotSent");

    /**
     * Override toString() to avoid using the enum variable name as the value, and instead use
     * the actual value defined in the API spec file.
     *
     * This solves a problem when the variable name and its value are different, and ensures that
     * the client sends the correct enum values to the server always.
     */
    override fun toString(): String = value

    companion object {
        /**
         * Converts the provided [data] to a [String] on success, null otherwise.
         */
        fun encode(data: kotlin.Any?): kotlin.String? = if (data is NotificationMessageState) "$data" else null

        /**
         * Returns a valid [NotificationMessageState] for [data], null otherwise.
         */
        fun decode(data: kotlin.Any?): NotificationMessageState? = data?.let {
          val normalizedData = "$it".lowercase()
          values().firstOrNull { value ->
            it == value || normalizedData == "$value".lowercase()
          }
        }
    }
}

