/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package loymax.sdk.models


import com.squareup.moshi.Json

/**
 * Текушее состояние нотификатора.
 *
 * Values: VERIFIED,UNVERIFIED
 */

enum class NotifierStatus(val value: kotlin.String) {

    @Json(name = "Verified")
    VERIFIED("Verified"),

    @Json(name = "Unverified")
    UNVERIFIED("Unverified");

    /**
     * Override toString() to avoid using the enum variable name as the value, and instead use
     * the actual value defined in the API spec file.
     *
     * This solves a problem when the variable name and its value are different, and ensures that
     * the client sends the correct enum values to the server always.
     */
    override fun toString(): String = value

    companion object {
        /**
         * Converts the provided [data] to a [String] on success, null otherwise.
         */
        fun encode(data: kotlin.Any?): kotlin.String? = if (data is NotifierStatus) "$data" else null

        /**
         * Returns a valid [NotifierStatus] for [data], null otherwise.
         */
        fun decode(data: kotlin.Any?): NotifierStatus? = data?.let {
          val normalizedData = "$it".lowercase()
          values().firstOrNull { value ->
            it == value || normalizedData == "$value".lowercase()
          }
        }
    }
}

