/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package loymax.sdk.models

import loymax.sdk.models.PlatformType
import loymax.sdk.models.PushServiceType

import com.squareup.moshi.Json

/**
 * Модель регистрации Push уведомления.
 *
 * @param token Токен.
 * @param platformType 
 * @param pushServiceType 
 */

data class NotificationRegisterModel (

    /* Токен. */
    @Json(name = "token")
    var token: kotlin.String? = null,

    @Json(name = "platformType")
    var platformType: PlatformType? = null,

    @Json(name = "pushServiceType")
    var pushServiceType: PushServiceType? = null

)

