/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package loymax.sdk.models

import loymax.sdk.models.OAuthProviderType

import com.squareup.moshi.Json

/**
 * 
 *
 * @param providerType 
 * @param groupId 
 */

data class OAuthUserGroupMember (

    @Json(name = "providerType")
    var providerType: OAuthProviderType? = null,

    @Json(name = "groupId")
    var groupId: kotlin.String? = null

)

