/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package loymax.sdk.models

import loymax.sdk.models.ClientApiSettings
import loymax.sdk.models.OAuthProtocolType
import loymax.sdk.models.OAuthProviderType
import loymax.sdk.models.OAuthUriSettings

import com.squareup.moshi.Json

/**
 * View-model для настроек клиентов социальных сетей.
 *
 * @param providerType 
 * @param id 
 * @param clientId 
 * @param clientSecret 
 * @param token 
 * @param name 
 * @param isActive 
 * @param protocol 
 * @param scope 
 * @param requestTokenUri 
 * @param authorizeUri 
 * @param accessTokenUri 
 * @param redirectUri 
 * @param apiSettings 
 * @param socialSetUri URL API метода привязки социального аккаунта.
 * @param socialLoginUri URL API метода логина социального аккаунта.
 */

data class OAuthSettingsViewModel (

    @Json(name = "providerType")
    var providerType: OAuthProviderType? = null,

    @Json(name = "id")
    var id: kotlin.Int? = null,

    @Json(name = "clientId")
    var clientId: kotlin.String? = null,

    @Json(name = "clientSecret")
    var clientSecret: kotlin.String? = null,

    @Json(name = "token")
    var token: kotlin.String? = null,

    @Json(name = "name")
    var name: kotlin.String? = null,

    @Json(name = "isActive")
    var isActive: kotlin.Boolean? = null,

    @Json(name = "protocol")
    var protocol: OAuthProtocolType? = null,

    @Json(name = "scope")
    var scope: kotlin.String? = null,

    @Json(name = "requestTokenUri")
    var requestTokenUri: OAuthUriSettings? = null,

    @Json(name = "authorizeUri")
    var authorizeUri: OAuthUriSettings? = null,

    @Json(name = "accessTokenUri")
    var accessTokenUri: OAuthUriSettings? = null,

    @Json(name = "redirectUri")
    var redirectUri: kotlin.String? = null,

    @Json(name = "apiSettings")
    var apiSettings: ClientApiSettings? = null,

    /* URL API метода привязки социального аккаунта. */
    @Json(name = "socialSetUri")
    var socialSetUri: kotlin.String? = null,

    /* URL API метода логина социального аккаунта. */
    @Json(name = "socialLoginUri")
    var socialLoginUri: kotlin.String? = null

)

