/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package loymax.sdk.models

import loymax.sdk.models.OfferCategoryViewModel
import loymax.sdk.models.OfferDraftState
import loymax.sdk.models.OfferState
import loymax.sdk.models.OfferViewState
import loymax.sdk.models.Operation
import loymax.sdk.models.PartnerLoyaltyProgramModel
import loymax.sdk.models.PartnerModel

import com.squareup.moshi.Json

/**
 * Модель для списка акций.
 *
 * @param id Внутренний идентификатор акции.
 * @param versionId Внутренний идентификатор версии акции.
 * @param name Название акции.
 * @param beginTime Дата начала действия акции.
 * @param endTime Дата окончания действия акции. (Null — если акция действует бесконечно долго, начиная с BeginTime).
 * @param operations 
 * @param creationDate Дата создания акции.
 * @param lastChangeDate Дата последних изменений.
 * @param creator Пользователь, создавший акцию.
 * @param lastChangeUser Пользователь, который последним редактировал акцию.
 * @param description Описание акции.
 * @param partners Список Партнеров акции.
 * @param isSum Признак суммируемости акции (true — акция суммируемая, false — акция несуммируемая).
 * @param priority Приоритет акции.
 * @param isDraft Является ли акция черновиком (true — акция является черновиком, false — акция не является черновиком).
 * @param isDefault Является ли акция базовой (для управления базовыми акциями требуется специальное право. True — акция базовая, false — акция не базовая).
 * @param offerCategory 
 * @param draftState 
 * @param draftLastChangeDate Дата последнего сохранения черновика.
 * @param externalID Внешний идентификатор акции (например, если акция была загружена через шлюз).
 * @param viewState 
 * @param state 
 * @param planned Признак наличия подтвержденных версий акции (true — акция еще не имеет подтвержденных версий и в периоде требуется выводить слово \"Планируется\").
 * @param draftRejectReason Причина отклонения версии как черновика акции.
 * @param loyaltyPrograms Программы лояльности.
 */

data class OfferBriefModel (

    /* Внутренний идентификатор акции. */
    @Json(name = "id")
    var id: kotlin.Int? = null,

    /* Внутренний идентификатор версии акции. */
    @Json(name = "versionId")
    var versionId: kotlin.Int? = null,

    /* Название акции. */
    @Json(name = "name")
    var name: kotlin.String? = null,

    /* Дата начала действия акции. */
    @Json(name = "beginTime")
    var beginTime: java.time.OffsetDateTime? = null,

    /* Дата окончания действия акции. (Null — если акция действует бесконечно долго, начиная с BeginTime). */
    @Json(name = "endTime")
    var endTime: java.time.OffsetDateTime? = null,

    @Json(name = "operations")
    var operations: Operation? = null,

    /* Дата создания акции. */
    @Json(name = "creationDate")
    var creationDate: java.time.OffsetDateTime? = null,

    /* Дата последних изменений. */
    @Json(name = "lastChangeDate")
    var lastChangeDate: java.time.OffsetDateTime? = null,

    /* Пользователь, создавший акцию. */
    @Json(name = "creator")
    var creator: kotlin.String? = null,

    /* Пользователь, который последним редактировал акцию. */
    @Json(name = "lastChangeUser")
    var lastChangeUser: kotlin.String? = null,

    /* Описание акции. */
    @Json(name = "description")
    var description: kotlin.String? = null,

    /* Список Партнеров акции. */
    @Json(name = "partners")
    var partners: kotlin.collections.MutableList<PartnerModel>? = null,

    /* Признак суммируемости акции (true — акция суммируемая, false — акция несуммируемая). */
    @Json(name = "isSum")
    var isSum: kotlin.Boolean? = null,

    /* Приоритет акции. */
    @Json(name = "priority")
    var priority: kotlin.Int? = null,

    /* Является ли акция черновиком (true — акция является черновиком, false — акция не является черновиком). */
    @Json(name = "isDraft")
    var isDraft: kotlin.Boolean? = null,

    /* Является ли акция базовой (для управления базовыми акциями требуется специальное право. True — акция базовая, false — акция не базовая). */
    @Json(name = "isDefault")
    var isDefault: kotlin.Boolean? = null,

    @Json(name = "offerCategory")
    var offerCategory: OfferCategoryViewModel? = null,

    @Json(name = "draftState")
    var draftState: OfferDraftState? = null,

    /* Дата последнего сохранения черновика. */
    @Json(name = "draftLastChangeDate")
    var draftLastChangeDate: java.time.OffsetDateTime? = null,

    /* Внешний идентификатор акции (например, если акция была загружена через шлюз). */
    @Json(name = "externalID")
    var externalID: kotlin.String? = null,

    @Json(name = "viewState")
    var viewState: OfferViewState? = null,

    @Json(name = "state")
    var state: OfferState? = null,

    /* Признак наличия подтвержденных версий акции (true — акция еще не имеет подтвержденных версий и в периоде требуется выводить слово \"Планируется\"). */
    @Json(name = "planned")
    var planned: kotlin.Boolean? = null,

    /* Причина отклонения версии как черновика акции. */
    @Json(name = "draftRejectReason")
    var draftRejectReason: kotlin.String? = null,

    /* Программы лояльности. */
    @Json(name = "loyaltyPrograms")
    var loyaltyPrograms: kotlin.collections.MutableList<PartnerLoyaltyProgramModel>? = null

)

