/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package loymax.sdk.models


import com.squareup.moshi.Json

/**
 * Ссылка на акцию.
 *
 * @param offerId Внешний идентификатор акции.
 * @param partnerId Идентификатор партнера акции.
 */

data class OfferLinkDto (

    /* Внешний идентификатор акции. */
    @Json(name = "offerId")
    var offerId: kotlin.String? = null,

    /* Идентификатор партнера акции. */
    @Json(name = "partnerId")
    var partnerId: java.util.UUID? = null

)

