/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package loymax.sdk.models

import loymax.sdk.models.ImportWarning

import com.squareup.moshi.Json

/**
 * Предупреждение, возникшие при импорте, с идентификатором акций.
 *
 * @param offerId Идентификатор акции.
 * @param warning 
 */

data class OfferImportWarning (

    /* Идентификатор акции. */
    @Json(name = "offerId")
    var offerId: kotlin.String? = null,

    @Json(name = "warning")
    var warning: ImportWarning? = null

)

