/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package loymax.sdk.models

import loymax.sdk.models.OfferDraftState

import com.squareup.moshi.Json

/**
 * 
 *
 * @param creationDate 
 * @param creator 
 * @param lastChangeDate 
 * @param lastChangeUser 
 * @param state 
 */

data class OfferDraftModel (

    @Json(name = "creationDate")
    var creationDate: java.time.OffsetDateTime? = null,

    @Json(name = "creator")
    var creator: kotlin.String? = null,

    @Json(name = "lastChangeDate")
    var lastChangeDate: java.time.OffsetDateTime? = null,

    @Json(name = "lastChangeUser")
    var lastChangeUser: kotlin.String? = null,

    @Json(name = "state")
    var state: OfferDraftState? = null

)

