/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package loymax.sdk.models

import loymax.sdk.models.OfferImportError
import loymax.sdk.models.OfferImportWarning

import com.squareup.moshi.Json

/**
 * Ответ на запрос импорта акций.
 *
 * @param inserted Количество новых акций.
 * @param updated Количество обновленных акций.
 * @param skipped Количество неизмененных акций.
 * @param errors Ошибки импорта по акциям.
 * @param offerImportWarnings Предупреждения, возникшие при импорте, с идентификаторами акций.
 */

data class OffersImportResponse (

    /* Количество новых акций. */
    @Json(name = "inserted")
    var inserted: kotlin.Int? = null,

    /* Количество обновленных акций. */
    @Json(name = "updated")
    var updated: kotlin.Int? = null,

    /* Количество неизмененных акций. */
    @Json(name = "skipped")
    var skipped: kotlin.Int? = null,

    /* Ошибки импорта по акциям. */
    @Json(name = "errors")
    var errors: kotlin.collections.MutableList<OfferImportError>? = null,

    /* Предупреждения, возникшие при импорте, с идентификаторами акций. */
    @Json(name = "offerImportWarnings")
    var offerImportWarnings: kotlin.collections.MutableList<OfferImportWarning>? = null

)

