/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package loymax.sdk.models

import loymax.sdk.models.LoyaltyProgramDto

import com.squareup.moshi.Json

/**
 * Программы лояльности, к которым относится акция.
 *
 * @param loyaltyPrograms Коллекция программ лояльности.
 */

data class OfferLoyaltyPrograms (

    /* Коллекция программ лояльности. */
    @Json(name = "loyaltyPrograms")
    var loyaltyPrograms: kotlin.collections.MutableList<LoyaltyProgramDto>? = null

)

