/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package loymax.sdk.models


import com.squareup.moshi.Json

/**
 * Информация об акции.
 *
 * @param id Внутренний идентификатор акции.
 * @param versionId Внутренний идентификатор версии акции.
 * @param name Название акции.
 * @param externalId Внешний идентификатор.
 * @param prerefenceValue Размер преференций.
 * @param quantity Размер позиции.
 * @param currencyAbbreviation Сокращенное название валюты.
 */

data class OfferResponseModel (

    /* Внутренний идентификатор акции. */
    @Json(name = "id")
    var id: kotlin.Int? = null,

    /* Внутренний идентификатор версии акции. */
    @Json(name = "versionId")
    var versionId: kotlin.Int? = null,

    /* Название акции. */
    @Json(name = "name")
    var name: kotlin.String? = null,

    /* Внешний идентификатор. */
    @Json(name = "externalId")
    var externalId: kotlin.String? = null,

    /* Размер преференций. */
    @Json(name = "prerefenceValue")
    var prerefenceValue: kotlin.Double? = null,

    /* Размер позиции. */
    @Json(name = "quantity")
    var quantity: kotlin.Double? = null,

    /* Сокращенное название валюты. */
    @Json(name = "currencyAbbreviation")
    var currencyAbbreviation: kotlin.String? = null

)

