/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package loymax.sdk.models


import com.squareup.moshi.Json

/**
 * 
 *
 * Values: PRIORITY,NAME,BEGIN_TIME,END_TIME,STATE,ATTACH_DATE,CREATION_DATE,CHANGE_DATE
 */

enum class OfferSortColumn(val value: kotlin.String) {

    @Json(name = "Priority")
    PRIORITY("Priority"),

    @Json(name = "Name")
    NAME("Name"),

    @Json(name = "BeginTime")
    BEGIN_TIME("BeginTime"),

    @Json(name = "EndTime")
    END_TIME("EndTime"),

    @Json(name = "State")
    STATE("State"),

    @Json(name = "AttachDate")
    ATTACH_DATE("AttachDate"),

    @Json(name = "CreationDate")
    CREATION_DATE("CreationDate"),

    @Json(name = "ChangeDate")
    CHANGE_DATE("ChangeDate");

    /**
     * Override toString() to avoid using the enum variable name as the value, and instead use
     * the actual value defined in the API spec file.
     *
     * This solves a problem when the variable name and its value are different, and ensures that
     * the client sends the correct enum values to the server always.
     */
    override fun toString(): String = value

    companion object {
        /**
         * Converts the provided [data] to a [String] on success, null otherwise.
         */
        fun encode(data: kotlin.Any?): kotlin.String? = if (data is OfferSortColumn) "$data" else null

        /**
         * Returns a valid [OfferSortColumn] for [data], null otherwise.
         */
        fun decode(data: kotlin.Any?): OfferSortColumn? = data?.let {
          val normalizedData = "$it".lowercase()
          values().firstOrNull { value ->
            it == value || normalizedData == "$value".lowercase()
          }
        }
    }
}

