/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package loymax.sdk.models


import com.squareup.moshi.Json

/**
 * Состояния версии как черновика              None = 0, версия не является черновиком (уже была подтверждена)              Edit = 1, версия является редактируемым в данный момент черновиком              Applied = 2, версия является черновиком, требующим подтверждения или отклонения (вносить изменения нельзя)              Rejected = 3,  версия является редактируемым в данный момент черновиком, отклоненным на этапе подтверждения.
 *
 * Values: none,edit,applied,rejected
 */

enum class OfferDraftState(val value: kotlin.String) {

    @Json(name = "None")
    none("None"),

    @Json(name = "Edit")
    edit("Edit"),

    @Json(name = "Applied")
    applied("Applied"),

    @Json(name = "Rejected")
    rejected("Rejected");

    /**
     * Override toString() to avoid using the enum variable name as the value, and instead use
     * the actual value defined in the API spec file.
     *
     * This solves a problem when the variable name and its value are different, and ensures that
     * the client sends the correct enum values to the server always.
     */
    override fun toString(): String = value

    companion object {
        /**
         * Converts the provided [data] to a [String] on success, null otherwise.
         */
        fun encode(data: kotlin.Any?): kotlin.String? = if (data is OfferDraftState) "$data" else null

        /**
         * Returns a valid [OfferDraftState] for [data], null otherwise.
         */
        fun decode(data: kotlin.Any?): OfferDraftState? = data?.let {
          val normalizedData = "$it".lowercase()
          values().firstOrNull { value ->
            it == value || normalizedData == "$value".lowercase()
          }
        }
    }
}

