/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package loymax.sdk.models

import loymax.sdk.models.OfferDto
import loymax.sdk.models.ProtocolVersion

import com.squareup.moshi.Json

/**
 * Модель импортируемых акций.
 *
 * @param version 
 * @param offers Акции.
 */

data class OffersImportModel (

    @Json(name = "version")
    var version: ProtocolVersion? = null,

    /* Акции. */
    @Json(name = "offers")
    var offers: kotlin.collections.MutableList<OfferDto>? = null

)

