/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package loymax.sdk.models

import loymax.sdk.models.DayOfWeek
import loymax.sdk.models.HourMinuteModel

import com.squareup.moshi.Json

/**
 * Модель для изменения приоритета акции.
 *
 * @param startDate Начало.
 * @param endDate Начало.
 * @param daysOfWeek Дни недели.
 * @param beginTime 
 * @param endTime 
 */

data class OfferPeriodModel (

    /* Начало. */
    @Json(name = "startDate")
    var startDate: java.time.OffsetDateTime? = null,

    /* Начало. */
    @Json(name = "endDate")
    var endDate: java.time.OffsetDateTime? = null,

    /* Дни недели. */
    @Json(name = "daysOfWeek")
    var daysOfWeek: kotlin.collections.MutableList<DayOfWeek>? = null,

    @Json(name = "beginTime")
    var beginTime: HourMinuteModel? = null,

    @Json(name = "endTime")
    var endTime: HourMinuteModel? = null

)

