/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package loymax.sdk.models


import com.squareup.moshi.Json

/**
 * View-модель переменной контекста.
 *
 * @param name Имя переменной.
 * @param displayName Отображаемое имя переменной.
 */

data class OfferEventContextVariableViewModel (

    /* Имя переменной. */
    @Json(name = "name")
    var name: kotlin.String? = null,

    /* Отображаемое имя переменной. */
    @Json(name = "displayName")
    var displayName: kotlin.String? = null

)

