/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package loymax.sdk.models

import loymax.sdk.models.PartnerViewModel

import com.squareup.moshi.Json

/**
 * Модель категории акции.
 *
 * @param id Внутренний идентификатор.
 * @param name Название.
 * @param logicalName Логическое имя.
 * @param partner 
 */

data class OfferCategoryViewModel (

    /* Внутренний идентификатор. */
    @Json(name = "id")
    var id: kotlin.Int? = null,

    /* Название. */
    @Json(name = "name")
    var name: kotlin.String? = null,

    /* Логическое имя. */
    @Json(name = "logicalName")
    var logicalName: kotlin.String? = null,

    @Json(name = "partner")
    var partner: PartnerViewModel? = null

)

