/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package loymax.sdk.models


import com.squareup.moshi.Json

/**
 * Старая-новая цена.
 *
 * @param oldPrice Старая цена.
 * @param newPrice Новая цена.
 */

data class OldNewPrice (

    /* Старая цена. */
    @Json(name = "oldPrice")
    var oldPrice: kotlin.String? = null,

    /* Новая цена. */
    @Json(name = "newPrice")
    var newPrice: kotlin.String? = null

)

