/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package loymax.sdk.models

import loymax.sdk.models.CardCompactInfoModel

import com.squareup.moshi.Json

/**
 * Модель результата регистрации.
 *
 * @param personId Внутренний идентификатор клиента.
 * @param personUID Идентификатор клиента.
 * @param mainCard 
 * @param virtualCard 
 */

data class OneTimeRegistrationResult (

    /* Внутренний идентификатор клиента. */
    @Json(name = "personId")
    var personId: kotlin.Int? = null,

    /* Идентификатор клиента. */
    @Json(name = "personUID")
    var personUID: java.util.UUID? = null,

    @Json(name = "mainCard")
    var mainCard: CardCompactInfoModel? = null,

    @Json(name = "virtualCard")
    var virtualCard: CardCompactInfoModel? = null

)

