/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package loymax.sdk.models

import loymax.sdk.models.IdentifierType

import com.squareup.moshi.Json

/**
 * Модель для фильтра операций пакетного начисления/списания.
 *
 * @param identifierType 
 * @param from Порядковый номер начального элемента выборки.
 * @param count Количество возвращаемых элементов выборки.
 * @param isCustomerIdNeeded Нужно ли для операций возвращать CustomerId.
 */

data class OperationsFilter (

    @Json(name = "identifierType")
    var identifierType: IdentifierType? = null,

    /* Порядковый номер начального элемента выборки. */
    @Json(name = "from")
    var from: kotlin.Int? = null,

    /* Количество возвращаемых элементов выборки. */
    @Json(name = "count")
    var count: kotlin.Int? = null,

    /* Нужно ли для операций возвращать CustomerId. */
    @Json(name = "isCustomerIdNeeded")
    var isCustomerIdNeeded: kotlin.Boolean? = null

)

