/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package loymax.sdk.models


import com.squareup.moshi.Json

/**
 * Тип операции.
 *
 * Values: paymentOperation,depositOperation,cashbackOperation,refundCashbackOperation,refundPaymentOperation,chargingOperation,directDiscountOperation,withdrawOperation,giftCardPaymentOperation,refundGiftCardPaymentOperation,giftCertificatePaymentOperation,refundGiftCertificatePaymentOperation
 */

enum class OperationsType(val value: kotlin.String) {

    @Json(name = "PaymentOperation")
    paymentOperation("PaymentOperation"),

    @Json(name = "DepositOperation")
    depositOperation("DepositOperation"),

    @Json(name = "CashbackOperation")
    cashbackOperation("CashbackOperation"),

    @Json(name = "RefundCashbackOperation")
    refundCashbackOperation("RefundCashbackOperation"),

    @Json(name = "RefundPaymentOperation")
    refundPaymentOperation("RefundPaymentOperation"),

    @Json(name = "ChargingOperation")
    chargingOperation("ChargingOperation"),

    @Json(name = "DirectDiscountOperation")
    directDiscountOperation("DirectDiscountOperation"),

    @Json(name = "WithdrawOperation")
    withdrawOperation("WithdrawOperation"),

    @Json(name = "GiftCardPaymentOperation")
    giftCardPaymentOperation("GiftCardPaymentOperation"),

    @Json(name = "RefundGiftCardPaymentOperation")
    refundGiftCardPaymentOperation("RefundGiftCardPaymentOperation"),

    @Json(name = "GiftCertificatePaymentOperation")
    giftCertificatePaymentOperation("GiftCertificatePaymentOperation"),

    @Json(name = "RefundGiftCertificatePaymentOperation")
    refundGiftCertificatePaymentOperation("RefundGiftCertificatePaymentOperation");

    /**
     * Override toString() to avoid using the enum variable name as the value, and instead use
     * the actual value defined in the API spec file.
     *
     * This solves a problem when the variable name and its value are different, and ensures that
     * the client sends the correct enum values to the server always.
     */
    override fun toString(): String = value

    companion object {
        /**
         * Converts the provided [data] to a [String] on success, null otherwise.
         */
        fun encode(data: kotlin.Any?): kotlin.String? = if (data is OperationsType) "$data" else null

        /**
         * Returns a valid [OperationsType] for [data], null otherwise.
         */
        fun decode(data: kotlin.Any?): OperationsType? = data?.let {
          val normalizedData = "$it".lowercase()
          values().firstOrNull { value ->
            it == value || normalizedData == "$value".lowercase()
          }
        }
    }
}

