/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package loymax.sdk.models

import loymax.sdk.models.IdentifierType

import com.squareup.moshi.Json

/**
 * Модель представления для операции. (Дублирует класс).
 *
 * @param identifierType 
 * @param identifier Значение идентификатора клиента.
 * @param description Описание операции.
 * @param amount Сумма начисления/списания.
 * @param externalInfo Внешний идентификатор начисления/списания.
 */

data class OperationDataModel (

    @Json(name = "identifierType")
    var identifierType: IdentifierType? = null,

    /* Значение идентификатора клиента. */
    @Json(name = "identifier")
    var identifier: kotlin.String? = null,

    /* Описание операции. */
    @Json(name = "description")
    var description: kotlin.String? = null,

    /* Сумма начисления/списания. */
    @Json(name = "amount")
    var amount: kotlin.Double? = null,

    /* Внешний идентификатор начисления/списания. */
    @Json(name = "externalInfo")
    var externalInfo: kotlin.String? = null

)

