/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package loymax.sdk.models


import com.squareup.moshi.Json

/**
 * Модель атрибутов Партнера.
 *
 * @param logicalName Логическое имя атрибута.
 * @param `value` Значение атрибута.
 * @param displayName Название для отображения.
 */

data class PartnerAttributeValueModel (

    /* Логическое имя атрибута. */
    @Json(name = "logicalName")
    var logicalName: kotlin.String? = null,

    /* Значение атрибута. */
    @Json(name = "value")
    var `value`: kotlin.String? = null,

    /* Название для отображения. */
    @Json(name = "displayName")
    var displayName: kotlin.String? = null

)

