/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package loymax.sdk.models

import loymax.sdk.models.NotifyType

import com.squareup.moshi.Json

/**
 * Модель шлюза Партнера.
 *
 * @param id Внутренний идентификатор шлюза.
 * @param name Название шлюза.
 * @param type 
 * @param code Код шлюза.
 * @param partnerId Внутренний идентификатор Партнера.
 */

data class PartnerNotifyGatewayViewModel (

    /* Внутренний идентификатор шлюза. */
    @Json(name = "id")
    var id: kotlin.Int? = null,

    /* Название шлюза. */
    @Json(name = "name")
    var name: kotlin.String? = null,

    @Json(name = "type")
    var type: NotifyType? = null,

    /* Код шлюза. */
    @Json(name = "code")
    var code: kotlin.String? = null,

    /* Внутренний идентификатор Партнера. */
    @Json(name = "partnerId")
    var partnerId: kotlin.Int? = null

)

