/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package loymax.sdk.models


import com.squareup.moshi.Json

/**
 * Действие акции \"Партнерские бонусы\".
 *
 * @param order Порядковый номер действия в цепочке.
 * @param id Id действия в цепочке.
 * @param currencyExternalId Для совместимости, использовать CurrencyUid: Uid валюты.
 * @param currencyUid Uid валюты.
 */

data class PartnerCashbackDiscountActionDto (

    /* Порядковый номер действия в цепочке. */
    @Json(name = "order")
    var order: kotlin.Int? = null,

    /* Id действия в цепочке. */
    @Json(name = "id")
    var id: kotlin.String? = null,

    /* Для совместимости, использовать CurrencyUid: Uid валюты. */
    @Json(name = "currencyExternalId")
    var currencyExternalId: kotlin.String? = null,

    /* Uid валюты. */
    @Json(name = "currencyUid")
    var currencyUid: kotlin.String? = null

)

