/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package loymax.sdk.models

import loymax.sdk.models.PasswordRuleType

import com.squareup.moshi.Json

/**
 * Требование к паролю.
 *
 * @param type 
 * @param expression Регулярное выражение для проверки.
 * @param description Описание требования.
 */

data class PasswordRequirementViewModel (

    @Json(name = "type")
    var type: PasswordRuleType? = null,

    /* Регулярное выражение для проверки. */
    @Json(name = "expression")
    var expression: kotlin.String? = null,

    /* Описание требования. */
    @Json(name = "description")
    var description: kotlin.String? = null

)

