/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package loymax.sdk.models


import com.squareup.moshi.Json

/**
 * Фильтр для типов оплаты.
 *
 * @param name Название типа оплаты.
 * @param count Количество элементов в выборке.
 * @param from С какого элемента начать выборку.
 */

data class PayTypeFilter (

    /* Название типа оплаты. */
    @Json(name = "name")
    var name: kotlin.String? = null,

    /* Количество элементов в выборке. */
    @Json(name = "count")
    var count: kotlin.Int? = null,

    /* С какого элемента начать выборку. */
    @Json(name = "from")
    var from: kotlin.Int? = null

)

