/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package loymax.sdk.models


import com.squareup.moshi.Json

/**
 * Модель представления способа оплаты.
 *
 * @param id Identifire.
 * @param name Название способа оплаты.
 * @param logicalName Логическое имя способа оплаты.
 * @param description Описание способа оплаты.
 * @param isDefault Признак дефолтного способа оплаты.
 * @param isArchived Признак архивности способа оплаты.
 */

data class PayTypeViewModel (

    /* Identifire. */
    @Json(name = "id")
    var id: kotlin.Int? = null,

    /* Название способа оплаты. */
    @Json(name = "name")
    var name: kotlin.String? = null,

    /* Логическое имя способа оплаты. */
    @Json(name = "logicalName")
    var logicalName: kotlin.String? = null,

    /* Описание способа оплаты. */
    @Json(name = "description")
    var description: kotlin.String? = null,

    /* Признак дефолтного способа оплаты. */
    @Json(name = "isDefault")
    var isDefault: kotlin.Boolean? = null,

    /* Признак архивности способа оплаты. */
    @Json(name = "isArchived")
    var isArchived: kotlin.Boolean? = null

)

