/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package loymax.sdk.models


import com.squareup.moshi.Json

/**
 * Описание типа персонального предложения и типа который его реализует.
 *
 * @param id Id Типа.
 * @param name Название.
 * @param description Описание.
 */

data class PersonalOfferTypeModel (

    /* Id Типа. */
    @Json(name = "id")
    var id: kotlin.String? = null,

    /* Название. */
    @Json(name = "name")
    var name: kotlin.String? = null,

    /* Описание. */
    @Json(name = "description")
    var description: kotlin.String? = null

)

