/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package loymax.sdk.models

import loymax.sdk.models.BrandViewModel
import loymax.sdk.models.DayOfWeek
import loymax.sdk.models.GoodsGroupViewModel
import loymax.sdk.models.PeriodClearCell
import loymax.sdk.models.TimePeriodType

import com.squareup.moshi.Json

/**
 * Модель представления для пользовательского атрибута типа \"Персональные товары\".
 *
 * @param id Идентификатор.
 * @param name Имя.
 * @param order Порядковый номер.
 * @param logicalName Логическое имя.
 * @param historyIsRecorded История записывается.
 * @param startFillDate Дата начала формирования пользовательского списка товаров.
 * @param endFillDate Дата окончания формирования пользовательского списка товаров.
 * @param maxGoodsCount Максимальное количество товаров, которые может выбрать пользователь.
 * @param defaultGoodsCount Количество товаров, которые может выбрать пользователь по умолчанию.
 * @param goodsGroup 
 * @param periodType 
 * @param periodClearCell 
 * @param dayOfWeek 
 * @param dayOfMonth День месяца.
 * @param daysOfPeriod Дней в периоде.
 * @param goodsCount Количество выбранных товаров.
 * @param brand 
 */

data class PersonalOfferAttributeViewModel (

    /* Идентификатор. */
    @Json(name = "id")
    var id: kotlin.Int? = null,

    /* Имя. */
    @Json(name = "name")
    var name: kotlin.String? = null,

    /* Порядковый номер. */
    @Json(name = "order")
    var order: kotlin.Int? = null,

    /* Логическое имя. */
    @Json(name = "logicalName")
    var logicalName: kotlin.String? = null,

    /* История записывается. */
    @Json(name = "historyIsRecorded")
    var historyIsRecorded: kotlin.Boolean? = null,

    /* Дата начала формирования пользовательского списка товаров. */
    @Json(name = "startFillDate")
    var startFillDate: java.time.OffsetDateTime? = null,

    /* Дата окончания формирования пользовательского списка товаров. */
    @Json(name = "endFillDate")
    var endFillDate: java.time.OffsetDateTime? = null,

    /* Максимальное количество товаров, которые может выбрать пользователь. */
    @Json(name = "maxGoodsCount")
    var maxGoodsCount: kotlin.Int? = null,

    /* Количество товаров, которые может выбрать пользователь по умолчанию. */
    @Json(name = "defaultGoodsCount")
    var defaultGoodsCount: kotlin.Int? = null,

    @Json(name = "goodsGroup")
    var goodsGroup: GoodsGroupViewModel? = null,

    @Json(name = "periodType")
    var periodType: TimePeriodType? = null,

    @Json(name = "periodClearCell")
    var periodClearCell: PeriodClearCell? = null,

    @Json(name = "dayOfWeek")
    var dayOfWeek: DayOfWeek? = null,

    /* День месяца. */
    @Json(name = "dayOfMonth")
    var dayOfMonth: kotlin.Int? = null,

    /* Дней в периоде. */
    @Json(name = "daysOfPeriod")
    var daysOfPeriod: kotlin.Int? = null,

    /* Количество выбранных товаров. */
    @Json(name = "goodsCount")
    var goodsCount: kotlin.Int? = null,

    @Json(name = "brand")
    var brand: BrandViewModel? = null

)

