/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package loymax.sdk.models

import loymax.sdk.models.UserAttributeType

import com.squareup.moshi.Json

/**
 * Модель атрибута клиента.
 *
 * @param id Идентификатор атрибута.
 * @param name Наименование атрибута.
 * @param userAttributeType 
 * @param type Тип атрибута.
 * @param logicalName Логическое имя.
 * @param fixedAnswers Варианты ответа.
 * @param order Порядковый номер.
 */

data class PersonAttributeModel (

    /* Идентификатор атрибута. */
    @Json(name = "id")
    var id: kotlin.Int? = null,

    /* Наименование атрибута. */
    @Json(name = "name")
    var name: kotlin.String? = null,

    @Json(name = "userAttributeType")
    var userAttributeType: UserAttributeType? = null,

    /* Тип атрибута. */
    @Json(name = "type")
    var type: kotlin.String? = null,

    /* Логическое имя. */
    @Json(name = "logicalName")
    var logicalName: kotlin.String? = null,

    /* Варианты ответа. */
    @Json(name = "fixedAnswers")
    var fixedAnswers: kotlin.collections.MutableList<kotlin.String>? = null,

    /* Порядковый номер. */
    @Json(name = "order")
    var order: kotlin.Int? = null

)

