/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package loymax.sdk.models

import loymax.sdk.models.PartnerDiscountType

import com.squareup.moshi.Json

/**
 * Фиксированная цена всех товаров.
 *
 * @param discountType 
 * @param `value` Значение скидки.
 */

data class PersonalOfferPriceDiscountViewModel (

    @Json(name = "discountType")
    var discountType: PartnerDiscountType? = null,

    /* Значение скидки. */
    @Json(name = "value")
    var `value`: kotlin.Double? = null

)

