/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package loymax.sdk.models

import loymax.sdk.models.PersonState

import com.squareup.moshi.Json

/**
 * Фильтр \"Состояние клиента\".
 *
 * @param name Имя фильтра.
 * @param processParameters Параметры обработки.
 * @param personStates Список состояний пользователя.
 */

data class PersonStateFilterDto (

    /* Имя фильтра. */
    @Json(name = "name")
    var name: kotlin.String? = null,

    /* Параметры обработки. */
    @Json(name = "processParameters")
    var processParameters: kotlin.String? = null,

    /* Список состояний пользователя. */
    @Json(name = "personStates")
    var personStates: kotlin.collections.MutableList<PersonState>? = null

)

