/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package loymax.sdk.models

import loymax.sdk.models.GoodsGroupModelInfo

import com.squareup.moshi.Json

/**
 * Модель представления для атрибута типа \"Персональные предложения\".
 *
 * @param id ID атрибута.
 * @param startFillDate Дата начала заполнения списка товаров.
 * @param endFillDate Дата окончания заполнения списка товаров.
 * @param maxGoodsCount Максимальное количество товаров.
 * @param goodsGroup 
 */

data class PersonalOfferAttributeModel (

    /* ID атрибута. */
    @Json(name = "id")
    var id: kotlin.Int? = null,

    /* Дата начала заполнения списка товаров. */
    @Json(name = "startFillDate")
    var startFillDate: java.time.OffsetDateTime? = null,

    /* Дата окончания заполнения списка товаров. */
    @Json(name = "endFillDate")
    var endFillDate: java.time.OffsetDateTime? = null,

    /* Максимальное количество товаров. */
    @Json(name = "maxGoodsCount")
    var maxGoodsCount: kotlin.Int? = null,

    @Json(name = "goodsGroup")
    var goodsGroup: GoodsGroupModelInfo? = null

)

