/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package loymax.sdk.models

import loymax.sdk.models.BrandShortModel
import loymax.sdk.models.ImageViewModel
import loymax.sdk.models.PersonalOfferAttributeModel

import com.squareup.moshi.Json

/**
 * Модель предтавления для персональных акций.
 *
 * @param id Идентификатор.
 * @param priority Приоритет рекламных материалов.
 * @param title Заголовок.
 * @param description Детальное описание.
 * @param shortDescription Краткое описание.
 * @param begin Начало действия.
 * @param end Окончание действия.
 * @param rewardThumbnail Вознаграждение.
 * @param rewardImageId Дополнительное изображение для вознаграждения.
 * @param brandIds Бренды.
 * @param brands Краткая информация о брендах.
 * @param brandId Бренд.
 * @param images Изображения.  TODO: подумать о вынесе в отдельный REST метод: v1/communication/offers/{id}/images.
 * @param instructions Условия акции.
 * @param merchantsCount Количество магазинов, в которых проходит акция.
 * @param attribute 
 * @param canSelectGoods Можно ли выбирать товары.
 */

data class PersonalOfferModel (

    /* Идентификатор. */
    @Json(name = "id")
    var id: kotlin.Int? = null,

    /* Приоритет рекламных материалов. */
    @Json(name = "priority")
    var priority: kotlin.Int? = null,

    /* Заголовок. */
    @Json(name = "title")
    var title: kotlin.String? = null,

    /* Детальное описание. */
    @Json(name = "description")
    var description: kotlin.String? = null,

    /* Краткое описание. */
    @Json(name = "shortDescription")
    var shortDescription: kotlin.String? = null,

    /* Начало действия. */
    @Json(name = "begin")
    var begin: java.time.OffsetDateTime? = null,

    /* Окончание действия. */
    @Json(name = "end")
    var end: java.time.OffsetDateTime? = null,

    /* Вознаграждение. */
    @Json(name = "rewardThumbnail")
    var rewardThumbnail: kotlin.Any? = null,

    /* Дополнительное изображение для вознаграждения. */
    @Json(name = "rewardImageId")
    var rewardImageId: java.util.UUID? = null,

    /* Бренды. */
    @Json(name = "brandIds")
    var brandIds: kotlin.collections.MutableList<java.util.UUID>? = null,

    /* Краткая информация о брендах. */
    @Json(name = "brands")
    var brands: kotlin.collections.MutableList<BrandShortModel>? = null,

    /* Бренд. */
    @Json(name = "brandId")
    var brandId: java.util.UUID? = null,

    /* Изображения.  TODO: подумать о вынесе в отдельный REST метод: v1/communication/offers/{id}/images. */
    @Json(name = "images")
    var images: kotlin.collections.MutableList<ImageViewModel>? = null,

    /* Условия акции. */
    @Json(name = "instructions")
    var instructions: kotlin.collections.MutableList<kotlin.String>? = null,

    /* Количество магазинов, в которых проходит акция. */
    @Json(name = "merchantsCount")
    var merchantsCount: kotlin.Int? = null,

    @Json(name = "attribute")
    var attribute: PersonalOfferAttributeModel? = null,

    /* Можно ли выбирать товары. */
    @Json(name = "canSelectGoods")
    var canSelectGoods: kotlin.Boolean? = null

)

