/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package loymax.sdk.models

import loymax.sdk.models.AccountChangeType

import com.squareup.moshi.Json

/**
 * Фильтр изменений по счету.
 *
 * @param fromDate Начальная дата выборки в формате 0000-00-00T00:00:00Z.
 * @param toDate Конечная дата выборки в формате 0000-00-00T00:00:00Z.
 * @param changeTypes Фильтр по типу изменения (активации/сгорания).
 * @param from Порядковый номер начального элемента выборки.
 * @param count Количество возвращаемых элементов выборки.
 */

data class PersonAccountChangesFilter (

    /* Начальная дата выборки в формате 0000-00-00T00:00:00Z. */
    @Json(name = "fromDate")
    var fromDate: java.time.OffsetDateTime? = null,

    /* Конечная дата выборки в формате 0000-00-00T00:00:00Z. */
    @Json(name = "toDate")
    var toDate: java.time.OffsetDateTime? = null,

    /* Фильтр по типу изменения (активации/сгорания). */
    @Json(name = "changeTypes")
    var changeTypes: kotlin.collections.MutableList<AccountChangeType>? = null,

    /* Порядковый номер начального элемента выборки. */
    @Json(name = "from")
    var from: kotlin.Int? = null,

    /* Количество возвращаемых элементов выборки. */
    @Json(name = "count")
    var count: kotlin.Int? = null

)

