/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package loymax.sdk.models


import com.squareup.moshi.Json

/**
 * Фильтр \"Привязка телефона\".
 *
 * @param name Имя фильтра.
 * @param processParameters Параметры обработки.
 * @param phoneBinded Привязан телефон или нет.
 */

data class PhoneBindingFilterDto (

    /* Имя фильтра. */
    @Json(name = "name")
    var name: kotlin.String? = null,

    /* Параметры обработки. */
    @Json(name = "processParameters")
    var processParameters: kotlin.String? = null,

    /* Привязан телефон или нет. */
    @Json(name = "phoneBinded")
    var phoneBinded: kotlin.Boolean? = null

)

