/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package loymax.sdk.models

import loymax.sdk.models.CountryViewModel
import loymax.sdk.models.PhoneMaskViewModel

import com.squareup.moshi.Json

/**
 * ViewModel для настроек телефона.
 *
 * @param id Id настройки.
 * @param prefix Префикс.
 * @param regexp Регулярное выражение.
 * @param masks Список масок для разных длин номеров.
 * @param country 
 * @param isArchived Помещен в архив или нет (архивный формат не используется в системе).
 * @param index Порядковый номер формата в выпадающем списке при вводе номера.
 */

data class PhoneSettingsViewModel (

    /* Id настройки. */
    @Json(name = "id")
    var id: kotlin.Int? = null,

    /* Префикс. */
    @Json(name = "prefix")
    var prefix: kotlin.Int? = null,

    /* Регулярное выражение. */
    @Json(name = "regexp")
    var regexp: kotlin.String? = null,

    /* Список масок для разных длин номеров. */
    @Json(name = "masks")
    var masks: kotlin.collections.MutableList<PhoneMaskViewModel>? = null,

    @Json(name = "country")
    var country: CountryViewModel? = null,

    /* Помещен в архив или нет (архивный формат не используется в системе). */
    @Json(name = "isArchived")
    var isArchived: kotlin.Boolean? = null,

    /* Порядковый номер формата в выпадающем списке при вводе номера. */
    @Json(name = "index")
    var index: kotlin.Int? = null

)

