/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package loymax.sdk.models


import com.squareup.moshi.Json

/**
 * Фильтр для получения списка настроек номеров телефонов.
 *
 * @param from Начало выборки.
 * @param count Количество.
 * @param countryName Название страны.
 * @param isArchived Активен формат или нет.
 */

data class PhoneSettingsFilter (

    /* Начало выборки. */
    @Json(name = "from")
    var from: kotlin.Int? = null,

    /* Количество. */
    @Json(name = "count")
    var count: kotlin.Int? = null,

    /* Название страны. */
    @Json(name = "countryName")
    var countryName: kotlin.String? = null,

    /* Активен формат или нет. */
    @Json(name = "isArchived")
    var isArchived: kotlin.Boolean? = null

)

