/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package loymax.sdk.models

import loymax.sdk.models.MoneyViewModel

import com.squareup.moshi.Json

/**
 * Модель возвратов в покупке.
 *
 * @param amount 
 */

data class PositionRefundsViewModel (

    @Json(name = "amount")
    var amount: MoneyViewModel? = null

)

