/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package loymax.sdk.models


import com.squareup.moshi.Json

/**
 * Модель для отправки кода подтверждения.
 *
 * @param confirmCode Код подтверждения.
 * @param password Пароль.
 */

data class PostConfirmCodeModel (

    /* Код подтверждения. */
    @Json(name = "confirmCode")
    var confirmCode: kotlin.String? = null,

    /* Пароль. */
    @Json(name = "password")
    var password: kotlin.String? = null

)

