/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package loymax.sdk.models

import loymax.sdk.models.MerchantDto

import com.squareup.moshi.Json

/**
 * Магазины, в которых совершались покупки.
 *
 * @param merchants Магазины, в которых совершались покупки.
 */

data class PurchaseFilterMerchants (

    /* Магазины, в которых совершались покупки. */
    @Json(name = "merchants")
    var merchants: kotlin.collections.MutableList<MerchantDto>? = null

)

