/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package loymax.sdk.models


import com.squareup.moshi.Json

/**
 * Тип операции покупки.
 *
 * Values: unknown,payment,deposit,cashback,refund,directDiscount,confirmPurchase,giftCardPayment,cancelPurchase,giftCertificatePayment,confirmRefundPurchase
 */

enum class PurchaseOperationType(val value: kotlin.String) {

    @Json(name = "Unknown")
    unknown("Unknown"),

    @Json(name = "Payment")
    payment("Payment"),

    @Json(name = "Deposit")
    deposit("Deposit"),

    @Json(name = "Cashback")
    cashback("Cashback"),

    @Json(name = "Refund")
    refund("Refund"),

    @Json(name = "DirectDiscount")
    directDiscount("DirectDiscount"),

    @Json(name = "ConfirmPurchase")
    confirmPurchase("ConfirmPurchase"),

    @Json(name = "GiftCardPayment")
    giftCardPayment("GiftCardPayment"),

    @Json(name = "CancelPurchase")
    cancelPurchase("CancelPurchase"),

    @Json(name = "GiftCertificatePayment")
    giftCertificatePayment("GiftCertificatePayment"),

    @Json(name = "ConfirmRefundPurchase")
    confirmRefundPurchase("ConfirmRefundPurchase");

    /**
     * Override toString() to avoid using the enum variable name as the value, and instead use
     * the actual value defined in the API spec file.
     *
     * This solves a problem when the variable name and its value are different, and ensures that
     * the client sends the correct enum values to the server always.
     */
    override fun toString(): String = value

    companion object {
        /**
         * Converts the provided [data] to a [String] on success, null otherwise.
         */
        fun encode(data: kotlin.Any?): kotlin.String? = if (data is PurchaseOperationType) "$data" else null

        /**
         * Returns a valid [PurchaseOperationType] for [data], null otherwise.
         */
        fun decode(data: kotlin.Any?): PurchaseOperationType? = data?.let {
          val normalizedData = "$it".lowercase()
          values().firstOrNull { value ->
            it == value || normalizedData == "$value".lowercase()
          }
        }
    }
}

