/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package loymax.sdk.models

import loymax.sdk.models.ChequePositionAttributeViewModel
import loymax.sdk.models.LegalViewModel
import loymax.sdk.models.MerchantViewModel
import loymax.sdk.models.PurchaseState

import com.squareup.moshi.Json

/**
 * View model покупки.
 *
 * @param purchaseId Идентификатор покупки.
 * @param purchaseTime Время покупки.
 * @param chequeNumber Номер чека.
 * @param completeTime Время завершения или отмены покупки.
 * @param deviceCode Kассир.
 * @param merchant 
 * @param legal 
 * @param state 
 * @param isFinalState Является ли состояние покупки конечным.
 * @param loyaltyProgramId Id программы лояльности.
 * @param personIdentifier Id покупателя (номер карты или телефон или...
 * @param couponNumbers Номера использованных купонов.
 * @param timeZone Часовой пояс.
 * @param chequeAdditionalAttributes Дополнительные аттрибуты чека.
 */

data class PurchaseViewModel (

    /* Идентификатор покупки. */
    @Json(name = "purchaseId")
    var purchaseId: kotlin.Int? = null,

    /* Время покупки. */
    @Json(name = "purchaseTime")
    var purchaseTime: java.time.OffsetDateTime? = null,

    /* Номер чека. */
    @Json(name = "chequeNumber")
    var chequeNumber: kotlin.String? = null,

    /* Время завершения или отмены покупки. */
    @Json(name = "completeTime")
    var completeTime: java.time.OffsetDateTime? = null,

    /* Kассир. */
    @Json(name = "deviceCode")
    var deviceCode: kotlin.String? = null,

    @Json(name = "merchant")
    var merchant: MerchantViewModel? = null,

    @Json(name = "legal")
    var legal: LegalViewModel? = null,

    @Json(name = "state")
    var state: PurchaseState? = null,

    /* Является ли состояние покупки конечным. */
    @Json(name = "isFinalState")
    var isFinalState: kotlin.Boolean? = null,

    /* Id программы лояльности. */
    @Json(name = "loyaltyProgramId")
    var loyaltyProgramId: kotlin.Int? = null,

    /* Id покупателя (номер карты или телефон или... */
    @Json(name = "personIdentifier")
    var personIdentifier: kotlin.String? = null,

    /* Номера использованных купонов. */
    @Json(name = "couponNumbers")
    var couponNumbers: kotlin.collections.MutableList<kotlin.String>? = null,

    /* Часовой пояс. */
    @Json(name = "timeZone")
    var timeZone: kotlin.Int? = null,

    /* Дополнительные аттрибуты чека. */
    @Json(name = "chequeAdditionalAttributes")
    var chequeAdditionalAttributes: kotlin.collections.MutableList<ChequePositionAttributeViewModel>? = null

)

