/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package loymax.sdk.models


import com.squareup.moshi.Json

/**
 * Тип Push-уведомления (для соответствующего типа).
 *
 * Values: GENERAL,ECHO,PERSONAL_OFFER
 */

enum class PushMessageType(val value: kotlin.String) {

    @Json(name = "General")
    GENERAL("General"),

    @Json(name = "Echo")
    ECHO("Echo"),

    @Json(name = "PersonalOffer")
    PERSONAL_OFFER("PersonalOffer");

    /**
     * Override toString() to avoid using the enum variable name as the value, and instead use
     * the actual value defined in the API spec file.
     *
     * This solves a problem when the variable name and its value are different, and ensures that
     * the client sends the correct enum values to the server always.
     */
    override fun toString(): String = value

    companion object {
        /**
         * Converts the provided [data] to a [String] on success, null otherwise.
         */
        fun encode(data: kotlin.Any?): kotlin.String? = if (data is PushMessageType) "$data" else null

        /**
         * Returns a valid [PushMessageType] for [data], null otherwise.
         */
        fun decode(data: kotlin.Any?): PushMessageType? = data?.let {
          val normalizedData = "$it".lowercase()
          values().firstOrNull { value ->
            it == value || normalizedData == "$value".lowercase()
          }
        }
    }
}

