/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package loymax.sdk.models


import com.squareup.moshi.Json

/**
 * Значение фильтра по строковому вопросу анкеты.
 *
 * @param `value` Строковое значение.
 */

data class QuestionnaireStringFilterValue (

    /* Строковое значение. */
    @Json(name = "value")
    var `value`: kotlin.String? = null

)

