/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package loymax.sdk.models

import loymax.sdk.models.ComparisonOperator
import loymax.sdk.models.DateMode
import loymax.sdk.models.DatePeriodicity
import loymax.sdk.models.DateUnit

import com.squareup.moshi.Json

/**
 * Значение фильтра по числовому вопросу анкеты.
 *
 * @param `operator` 
 * @param mode 
 * @param periodicity 
 * @param unit 
 * @param startOfPeriod 
 * @param firstValue Первое значение.
 * @param secondValue Второе значение.
 */

data class QuestionnaireIntFilterValue (

    @Json(name = "operator")
    var `operator`: ComparisonOperator? = null,

    @Json(name = "mode")
    var mode: DateMode? = null,

    @Json(name = "periodicity")
    var periodicity: DatePeriodicity? = null,

    @Json(name = "unit")
    var unit: DateUnit? = null,

    @Json(name = "startOfPeriod")
    var startOfPeriod: DateUnit? = null,

    /* Первое значение. */
    @Json(name = "firstValue")
    var firstValue: kotlin.Int? = null,

    /* Второе значение. */
    @Json(name = "secondValue")
    var secondValue: kotlin.Int? = null

)

