/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package loymax.sdk.models


import com.squareup.moshi.Json

/**
 * View-модель конфигурации регулярного выражения.
 *
 * @param id Идентификатор.
 * @param name Название.
 * @param expression Регулярное выражение.
 * @param description Описание.
 * @param errorMessage Сообщение об ошибке.
 */

data class RegexpConfigurationViewModel (

    /* Идентификатор. */
    @Json(name = "id")
    var id: kotlin.Int? = null,

    /* Название. */
    @Json(name = "name")
    var name: kotlin.String? = null,

    /* Регулярное выражение. */
    @Json(name = "expression")
    var expression: kotlin.String? = null,

    /* Описание. */
    @Json(name = "description")
    var description: kotlin.String? = null,

    /* Сообщение об ошибке. */
    @Json(name = "errorMessage")
    var errorMessage: kotlin.String? = null

)

