/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package loymax.sdk.models


import com.squareup.moshi.Json

/**
 * Входные данные для регистрации.
 *
 * @param login Логин.
 * @param password Пароль.
 * @param withoutCall Регистрация начата без звонка.
 * @param cvcCode CVC-код.
 */

data class RegistrationModel (

    /* Логин. */
    @Json(name = "login")
    var login: kotlin.String? = null,

    /* Пароль. */
    @Json(name = "password")
    var password: kotlin.String? = null,

    /* Регистрация начата без звонка. */
    @Json(name = "withoutCall")
    var withoutCall: kotlin.Boolean? = null,

    /* CVC-код. */
    @Json(name = "cvcCode")
    var cvcCode: kotlin.String? = null

)

