/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package loymax.sdk.models

import loymax.sdk.models.AuthResultModel
import loymax.sdk.models.ReplaceCardState

import com.squareup.moshi.Json

/**
 * Результат замены карты.
 *
 * @param replaceCardState 
 * @param errorMessage Текст ошибки.
 * @param authResult 
 */

data class ReplaceCardResult (

    @Json(name = "replaceCardState")
    var replaceCardState: ReplaceCardState? = null,

    /* Текст ошибки. */
    @Json(name = "errorMessage")
    var errorMessage: kotlin.String? = null,

    @Json(name = "authResult")
    var authResult: AuthResultModel? = null

)

