/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package loymax.sdk.models


import com.squareup.moshi.Json

/**
 * Модель данных для восстановления пароля.
 *
 * @param identifier Идентификатор пользователя.
 */

data class ResetPasswordInfoSearchModel (

    /* Идентификатор пользователя. */
    @Json(name = "identifier")
    var identifier: kotlin.String? = null

)

