/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package loymax.sdk.models

import loymax.sdk.models.ResetPasswordIdentifierInfoModel

import com.squareup.moshi.Json

/**
 * Информация для возможных вариантов восстановления пароля.
 *
 * @param firstName Имя пользователя.
 * @param lastName Фамилия.
 * @param identifiers Список идентификаторов для восстановления.
 */

data class ResetPasswordInfoModel (

    /* Имя пользователя. */
    @Json(name = "firstName")
    var firstName: kotlin.String? = null,

    /* Фамилия. */
    @Json(name = "lastName")
    var lastName: kotlin.String? = null,

    /* Список идентификаторов для восстановления. */
    @Json(name = "identifiers")
    var identifiers: kotlin.collections.MutableList<ResetPasswordIdentifierInfoModel>? = null

)

