/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package loymax.sdk.models

import loymax.sdk.models.Result

import com.squareup.moshi.Json

/**
 * Модель результата.
 *
 * @param result 
 */

interface ResultModel {

    @Json(name = "result")
    var result: Result?
}

