/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package loymax.sdk.models


import com.squareup.moshi.Json

/**
 * Модель описания акции.
 *
 * @param id Идентификатор.
 */

data class RewardThumbnailModel (

    /* Идентификатор. */
    @Json(name = "id")
    var id: kotlin.Int? = null

)

