/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package loymax.sdk.models


import com.squareup.moshi.Json

/**
 * Модель роли.
 *
 * @param id Идентификатор роли.
 * @param name Название роли.
 * @param logicalName Логическое название роли.
 * @param permissions Набор прав доступа, доступных участнику с данной ролью.
 */

data class RoleModel (

    /* Идентификатор роли. */
    @Json(name = "id")
    var id: kotlin.Int? = null,

    /* Название роли. */
    @Json(name = "name")
    var name: kotlin.String? = null,

    /* Логическое название роли. */
    @Json(name = "logicalName")
    var logicalName: kotlin.String? = null,

    /* Набор прав доступа, доступных участнику с данной ролью. */
    @Json(name = "permissions")
    var permissions: kotlin.collections.MutableList<kotlin.String>? = null

)

