/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package loymax.sdk.models

import loymax.sdk.models.CardState

import com.squareup.moshi.Json

/**
 * 
 *
 * @param cardState 
 * @param isGift 
 * @param isBlocked 
 */

data class SearchByCardAttributesModel (

    @Json(name = "cardState")
    var cardState: CardState? = null,

    @Json(name = "isGift")
    var isGift: kotlin.Boolean? = null,

    @Json(name = "isBlocked")
    var isBlocked: kotlin.Boolean? = null

)

