/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package loymax.sdk.models


import com.squareup.moshi.Json

/**
 * Модель для отправки нового пароля Участнику ПЛ.
 *
 * @param personID Внутренний идентификатор Участника ПЛ.
 */

data class SendNewPasswordModel (

    /* Внутренний идентификатор Участника ПЛ. */
    @Json(name = "personID")
    var personID: kotlin.Int? = null

)

