/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package loymax.sdk.models

import loymax.sdk.models.CustomerActionType

import com.squareup.moshi.Json

/**
 * Информация о привязке email.
 *
 * @param emailAddress Привязываемый адрес электронной почты.
 * @param emailAttachType 
 * @param emailAttachSourceId Источник привязки электронной почты.
 */

data class SetEmailViewModel (

    /* Привязываемый адрес электронной почты. */
    @Json(name = "emailAddress")
    var emailAddress: kotlin.String? = null,

    @Json(name = "emailAttachType")
    var emailAttachType: CustomerActionType? = null,

    /* Источник привязки электронной почты. */
    @Json(name = "emailAttachSourceId")
    var emailAttachSourceId: kotlin.String? = null

)

