/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package loymax.sdk.models


import com.squareup.moshi.Json

/**
 * Простая модель категории рекламных материалов.
 *
 * @param id Идентификатор категории.
 * @param name Имя категории.
 * @param isArchived Находится ли в архиве.
 */

data class SimpleCategoryViewModel (

    /* Идентификатор категории. */
    @Json(name = "id")
    var id: kotlin.Int? = null,

    /* Имя категории. */
    @Json(name = "name")
    var name: kotlin.String? = null,

    /* Находится ли в архиве. */
    @Json(name = "isArchived")
    var isArchived: kotlin.Boolean? = null

)

