/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package loymax.sdk.models

import loymax.sdk.models.OAuthActivityType
import loymax.sdk.models.OAuthProviderType

import com.squareup.moshi.Json

/**
 * View-model для фильтра \"Активность в социальных сетях\".
 *
 * @param id 
 * @param name 
 * @param isDeletedFilterType 
 * @param processParameters 
 * @param providerType 
 * @param activityType 
 * @param objects Отслеживаемые объекты.
 */

data class SocialActivityFilterViewModel (

    @Json(name = "id")
    var id: kotlin.Int? = null,

    @Json(name = "name")
    var name: kotlin.String? = null,

    @Json(name = "isDeletedFilterType")
    var isDeletedFilterType: kotlin.Boolean? = null,

    @Json(name = "processParameters")
    var processParameters: kotlin.String? = null,

    @Json(name = "providerType")
    var providerType: OAuthProviderType? = null,

    @Json(name = "activityType")
    var activityType: OAuthActivityType? = null,

    /* Отслеживаемые объекты. */
    @Json(name = "objects")
    var objects: kotlin.String? = null

)

