/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package loymax.sdk.models

import loymax.sdk.models.ComparisonOperator
import loymax.sdk.models.StatusValueType

import com.squareup.moshi.Json

/**
 * Фильтр по статусной системе.
 *
 * @param name Имя фильтра.
 * @param processParameters Параметры обработки.
 * @param attributeId Идентификатор атрибута.
 * @param statusValueType 
 * @param operation 
 * @param propertyValues Значения для сравнения.
 */

data class StatusSystemUserAttributeFilterDto (

    /* Имя фильтра. */
    @Json(name = "name")
    var name: kotlin.String? = null,

    /* Параметры обработки. */
    @Json(name = "processParameters")
    var processParameters: kotlin.String? = null,

    /* Идентификатор атрибута. */
    @Json(name = "attributeId")
    var attributeId: kotlin.Int? = null,

    @Json(name = "statusValueType")
    var statusValueType: StatusValueType? = null,

    @Json(name = "operation")
    var operation: ComparisonOperator? = null,

    /* Значения для сравнения. */
    @Json(name = "values")
    var propertyValues: kotlin.collections.MutableList<kotlin.Int>? = null

)

