/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package loymax.sdk.models

import loymax.sdk.models.AttributesMergeMode
import loymax.sdk.models.CounterViewModel
import loymax.sdk.models.SystemApiStatusViewModel
import loymax.sdk.models.TimeUnit

import com.squareup.moshi.Json

/**
 * ViewModel для статусной системы.
 *
 * @param id Идентификатор.
 * @param name Имя.
 * @param order Порядковый номер.
 * @param logicalName Логическое имя.
 * @param historyIsRecorded История записывается.
 * @param statuses Статусы.
 * @param isHidden Видимость.
 * @param mergeMode 
 * @param isDeleted Удален ли атрибут.
 * @param description Описание.
 * @param fileExternalId Идентификатор файла с описанием.
 * @param statusUpdatePeriod 
 * @param counter 
 */

data class StatusSystemAttributeViewModel (

    /* Идентификатор. */
    @Json(name = "id")
    var id: kotlin.Int? = null,

    /* Имя. */
    @Json(name = "name")
    var name: kotlin.String? = null,

    /* Порядковый номер. */
    @Json(name = "order")
    var order: kotlin.Int? = null,

    /* Логическое имя. */
    @Json(name = "logicalName")
    var logicalName: kotlin.String? = null,

    /* История записывается. */
    @Json(name = "historyIsRecorded")
    var historyIsRecorded: kotlin.Boolean? = null,

    /* Статусы. */
    @Json(name = "statuses")
    var statuses: kotlin.collections.MutableList<SystemApiStatusViewModel>? = null,

    /* Видимость. */
    @Json(name = "isHidden")
    var isHidden: kotlin.Boolean? = null,

    @Json(name = "mergeMode")
    var mergeMode: AttributesMergeMode? = null,

    /* Удален ли атрибут. */
    @Json(name = "isDeleted")
    var isDeleted: kotlin.Boolean? = null,

    /* Описание. */
    @Json(name = "description")
    var description: kotlin.String? = null,

    /* Идентификатор файла с описанием. */
    @Json(name = "fileExternalId")
    var fileExternalId: java.util.UUID? = null,

    @Json(name = "statusUpdatePeriod")
    var statusUpdatePeriod: TimeUnit? = null,

    @Json(name = "counter")
    var counter: CounterViewModel? = null

)

