/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package loymax.sdk.models


import com.squareup.moshi.Json

/**
 * Модель StringValue.
 *
 * @param stringValue StringValue.
 */

data class StringValueModel (

    /* StringValue. */
    @Json(name = "stringValue")
    var stringValue: kotlin.String? = null

)

