/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package loymax.sdk.models


import com.squareup.moshi.Json

/**
 * Модель номеров магнитных дорожек.
 *
 * @param strip1 Магнитная дорожка №1.
 * @param strip2 Магнитная дорожка №2.
 * @param strip3 Магнитная дорожка №3.
 */

data class StripNumbers (

    /* Магнитная дорожка №1. */
    @Json(name = "strip1")
    var strip1: kotlin.String? = null,

    /* Магнитная дорожка №2. */
    @Json(name = "strip2")
    var strip2: kotlin.String? = null,

    /* Магнитная дорожка №3. */
    @Json(name = "strip3")
    var strip3: kotlin.String? = null

)

