/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package loymax.sdk.models


import com.squareup.moshi.Json

/**
 * Базовая модель пользователя системы.
 *
 * @param firstName Имя.
 * @param lastName Фамилия.
 * @param patronymicName Отчество.
 * @param phone Телефон.
 * @param email Email.
 * @param timeZone Часовой пояс.
 */

data class SystemUserBaseViewModel (

    /* Имя. */
    @Json(name = "firstName")
    var firstName: kotlin.String? = null,

    /* Фамилия. */
    @Json(name = "lastName")
    var lastName: kotlin.String? = null,

    /* Отчество. */
    @Json(name = "patronymicName")
    var patronymicName: kotlin.String? = null,

    /* Телефон. */
    @Json(name = "phone")
    var phone: kotlin.String? = null,

    /* Email. */
    @Json(name = "email")
    var email: kotlin.String? = null,

    /* Часовой пояс. */
    @Json(name = "timeZone")
    var timeZone: kotlin.Int? = null

)

