/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package loymax.sdk.models


import com.squareup.moshi.Json

/**
 * Модель целевой аудитории.
 *
 * @param name Название.
 * @param description Описание.
 * @param partnerId Внутренний идентификатор Партнера.
 * @param loyaltyProgramId Внутренний идентификатор Программы лояльности.
 * @param isExternal Тип целевой аудитории.
 */

data class TargetGroupModel (

    /* Название. */
    @Json(name = "name")
    var name: kotlin.String? = null,

    /* Описание. */
    @Json(name = "description")
    var description: kotlin.String? = null,

    /* Внутренний идентификатор Партнера. */
    @Json(name = "partnerId")
    var partnerId: kotlin.Int? = null,

    /* Внутренний идентификатор Программы лояльности. */
    @Json(name = "loyaltyProgramId")
    var loyaltyProgramId: kotlin.Int? = null,

    /* Тип целевой аудитории. */
    @Json(name = "isExternal")
    var isExternal: kotlin.Boolean? = null

)

