/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package loymax.sdk.models

import loymax.sdk.models.CalculationModel
import loymax.sdk.models.TargetGroupSegmentationType

import com.squareup.moshi.Json

/**
 * Модель сегмента целевой аудитории.
 *
 * @param id Внутренний идентификатор сегмента.
 * @param name Название сегмента.
 * @param isArchived Признак состояния сегмента (true - удален, false - не удален).
 * @param type 
 * @param calculationInfo 
 */

data class TargetGroupSegmentViewModel (

    /* Внутренний идентификатор сегмента. */
    @Json(name = "id")
    var id: kotlin.Int? = null,

    /* Название сегмента. */
    @Json(name = "name")
    var name: kotlin.String? = null,

    /* Признак состояния сегмента (true - удален, false - не удален). */
    @Json(name = "isArchived")
    var isArchived: kotlin.Boolean? = null,

    @Json(name = "type")
    var type: TargetGroupSegmentationType? = null,

    @Json(name = "calculationInfo")
    var calculationInfo: CalculationModel? = null

)

