/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package loymax.sdk.models

import loymax.sdk.models.TargetGroupSegmentationType

import com.squareup.moshi.Json

/**
 * Модель фильтра сегмента ЦА.
 *
 * @param type 
 */

data class TargetGroupSegmentFilterTypeModel (

    @Json(name = "type")
    var type: TargetGroupSegmentationType? = null

)

