/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package loymax.sdk.models


import com.squareup.moshi.Json

/**
 * Фильтр \"Целевые аудитории\".
 *
 * @param name Имя фильтра.
 * @param processParameters Параметры обработки.
 * @param targetGroups Список выбранных целевых аудиторий.
 */

data class TargetGroupFilterDto (

    /* Имя фильтра. */
    @Json(name = "name")
    var name: kotlin.String? = null,

    /* Параметры обработки. */
    @Json(name = "processParameters")
    var processParameters: kotlin.String? = null,

    /* Список выбранных целевых аудиторий. */
    @Json(name = "targetGroups")
    var targetGroups: kotlin.collections.MutableList<kotlin.Any>? = null

)

