/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package loymax.sdk.models

import loymax.sdk.models.LimitTypeNotificationFrequency

import com.squareup.moshi.Json

/**
 * Действия для оповещения по электронной почте.
 *
 * @param id Идентификатор.
 * @param isArchived В архивном состоянии или нет.
 * @param frequency 
 * @param message Текст уведомления.
 * @param email Адрес электронной почты.
 * @param header Заголовок сообщения.
 */

data class TemplateEmailViewModel (

    /* Идентификатор. */
    @Json(name = "id")
    var id: kotlin.Int? = null,

    /* В архивном состоянии или нет. */
    @Json(name = "isArchived")
    var isArchived: kotlin.Boolean? = null,

    @Json(name = "frequency")
    var frequency: LimitTypeNotificationFrequency? = null,

    /* Текст уведомления. */
    @Json(name = "message")
    var message: kotlin.String? = null,

    /* Адрес электронной почты. */
    @Json(name = "email")
    var email: kotlin.String? = null,

    /* Заголовок сообщения. */
    @Json(name = "header")
    var header: kotlin.String? = null

)

