/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package loymax.sdk.models


import com.squareup.moshi.Json

/**
 * 
 *
 * @param name 
 * @param isDeleted 
 * @param from 
 * @param count 
 * @param loyaltyProgramsIds 
 * @param partnersIds 
 * @param authorsIds 
 */

data class TemplateSetFilterModel (

    @Json(name = "name")
    var name: kotlin.String? = null,

    @Json(name = "isDeleted")
    var isDeleted: kotlin.Boolean? = null,

    @Json(name = "from")
    var from: kotlin.Int? = null,

    @Json(name = "count")
    var count: kotlin.Int? = null,

    @Json(name = "loyaltyProgramsIds")
    var loyaltyProgramsIds: kotlin.collections.MutableList<kotlin.Int>? = null,

    @Json(name = "partnersIds")
    var partnersIds: kotlin.collections.MutableList<kotlin.Int>? = null,

    @Json(name = "authorsIds")
    var authorsIds: kotlin.collections.MutableList<kotlin.Int>? = null

)

