/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package loymax.sdk.models

import loymax.sdk.models.TimeUnitsLimit

import com.squareup.moshi.Json

/**
 * 
 *
 * @param `value` 
 * @param unit 
 */

data class TimeModel (

    @Json(name = "value")
    var `value`: kotlin.Int? = null,

    @Json(name = "unit")
    var unit: TimeUnitsLimit? = null

)

