/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package loymax.sdk.models


import com.squareup.moshi.Json

/**
 * View-модель для триггерной рассылки.
 *
 * @param id Идентификатор рассылки.
 * @param name Название рассылки.
 */

data class TriggeredMailingViewModel (

    /* Идентификатор рассылки. */
    @Json(name = "id")
    var id: kotlin.Int? = null,

    /* Название рассылки. */
    @Json(name = "name")
    var name: kotlin.String? = null

)

