/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package loymax.sdk.models


import com.squareup.moshi.Json

/**
 * Модель статуса клиента.
 *
 * @param statusSystemId Внутренний идентификатор статусной системы.
 * @param statusId Внутренний идентификатор статуса.
 * @param comment Причина изменения.
 */

data class UpdatePersonStatusViewModel (

    /* Внутренний идентификатор статусной системы. */
    @Json(name = "statusSystemId")
    var statusSystemId: kotlin.Int? = null,

    /* Внутренний идентификатор статуса. */
    @Json(name = "statusId")
    var statusId: kotlin.Int? = null,

    /* Причина изменения. */
    @Json(name = "comment")
    var comment: kotlin.String? = null

)

