/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package loymax.sdk.models


import com.squareup.moshi.Json

/**
 * Информация о пользователе.
 *
 * @param id Идентификатор пользователя.
 * @param personUid Уникальный идентификатор пользователя.
 * @param firstName Имя.
 * @param lastName Фамилия.
 * @param patronymicName Отчество.
 * @param phoneNumber Номер телефона.
 * @param email Email.
 */

data class UserInfoBase (

    /* Идентификатор пользователя. */
    @Json(name = "id")
    var id: kotlin.Int? = null,

    /* Уникальный идентификатор пользователя. */
    @Json(name = "personUid")
    var personUid: java.util.UUID? = null,

    /* Имя. */
    @Json(name = "firstName")
    var firstName: kotlin.String? = null,

    /* Фамилия. */
    @Json(name = "lastName")
    var lastName: kotlin.String? = null,

    /* Отчество. */
    @Json(name = "patronymicName")
    var patronymicName: kotlin.String? = null,

    /* Номер телефона. */
    @Json(name = "phoneNumber")
    var phoneNumber: kotlin.String? = null,

    /* Email. */
    @Json(name = "email")
    var email: kotlin.String? = null

)

