/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package loymax.sdk.models

import loymax.sdk.models.RoleModel

import com.squareup.moshi.Json

/**
 * Модель роли для идентификатора.
 *
 * @param role 
 * @param partnerIds Партнеры.
 */

data class UserRoleModel (

    @Json(name = "role")
    var role: RoleModel? = null,

    /* Партнеры. */
    @Json(name = "partnerIds")
    var partnerIds: kotlin.collections.MutableList<kotlin.Int>? = null

)

