/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package loymax.sdk.models

import loymax.sdk.models.ActionState
import loymax.sdk.models.UserActionType

import com.squareup.moshi.Json

/**
 * Информация о действиях клиента.
 *
 * @param userActionType 
 * @param actionState 
 * @param isDone Является ли действие выполненным (true-выполнено, false-не выполнено).
 */

data class UserActionModel (

    @Json(name = "userActionType")
    var userActionType: UserActionType? = null,

    @Json(name = "actionState")
    var actionState: ActionState? = null,

    /* Является ли действие выполненным (true-выполнено, false-не выполнено). */
    @Json(name = "isDone")
    var isDone: kotlin.Boolean? = null

)

