/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package loymax.sdk.models

import loymax.sdk.models.AttributesMergeMode
import loymax.sdk.models.CommonAttributeValueType
import loymax.sdk.models.Item

import com.squareup.moshi.Json

/**
 * ViewModel для атрибута пользователя.
 *
 * @param id Идентификатор.
 * @param name Имя.
 * @param order Порядковый номер.
 * @param logicalName Логическое имя.
 * @param historyIsRecorded История записывается.
 * @param type 
 * @param params Параметры атрибута.
 * @param description Описание.
 * @param mergeMode 
 * @param required Обязательность атрибута.
 * @param isDeleted Удален ли атрибут.
 * @param isHidden Видимость.
 * @param isDynamic Динамический ли атрибут.
 * @param items Доступные значения  (для типа {!:RadioString}).
 * @param hasMultipleValues Имеет ли атрибут множественные значения.
 * @param useTemplateEngine Использовать шаблонизатор.
 */

data class UserAttributeViewModel (

    /* Идентификатор. */
    @Json(name = "id")
    var id: kotlin.Int? = null,

    /* Имя. */
    @Json(name = "name")
    var name: kotlin.String? = null,

    /* Порядковый номер. */
    @Json(name = "order")
    var order: kotlin.Int? = null,

    /* Логическое имя. */
    @Json(name = "logicalName")
    var logicalName: kotlin.String? = null,

    /* История записывается. */
    @Json(name = "historyIsRecorded")
    var historyIsRecorded: kotlin.Boolean? = null,

    @Json(name = "type")
    var type: CommonAttributeValueType? = null,

    /* Параметры атрибута. */
    @Json(name = "params")
    var params: kotlin.String? = null,

    /* Описание. */
    @Json(name = "description")
    var description: kotlin.String? = null,

    @Json(name = "mergeMode")
    var mergeMode: AttributesMergeMode? = null,

    /* Обязательность атрибута. */
    @Json(name = "required")
    var required: kotlin.Boolean? = null,

    /* Удален ли атрибут. */
    @Json(name = "isDeleted")
    var isDeleted: kotlin.Boolean? = null,

    /* Видимость. */
    @Json(name = "isHidden")
    var isHidden: kotlin.Boolean? = null,

    /* Динамический ли атрибут. */
    @Json(name = "isDynamic")
    var isDynamic: kotlin.Boolean? = null,

    /* Доступные значения  (для типа {!:RadioString}). */
    @Json(name = "items")
    var items: kotlin.collections.MutableList<Item>? = null,

    /* Имеет ли атрибут множественные значения. */
    @Json(name = "hasMultipleValues")
    var hasMultipleValues: kotlin.Boolean? = null,

    /* Использовать шаблонизатор. */
    @Json(name = "useTemplateEngine")
    var useTemplateEngine: kotlin.Boolean? = null

)

