/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package loymax.sdk.models


import com.squareup.moshi.Json

/**
 * Ошибки при обновлении значения атрибута.
 *
 * @param messages Список сообщений.
 */

data class UserAttributeValueUpdateError (

    /* Список сообщений. */
    @Json(name = "messages")
    var messages: kotlin.collections.MutableList<kotlin.String>? = null

)

