/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package loymax.sdk.models

import loymax.sdk.models.NewPhoneNumberInfo

import com.squareup.moshi.Json

/**
 * Информация о номере телефона клиента.
 *
 * @param currentPhoneNumber Текущий привязанный номер телефона.
 * @param newPhoneNumber 
 * @param confirmCodeLength Длина кода подтверждения.
 */

data class UserPhoneNumberInfo (

    /* Текущий привязанный номер телефона. */
    @Json(name = "currentPhoneNumber")
    var currentPhoneNumber: kotlin.String? = null,

    @Json(name = "newPhoneNumber")
    var newPhoneNumber: NewPhoneNumberInfo? = null,

    /* Длина кода подтверждения. */
    @Json(name = "confirmCodeLength")
    var confirmCodeLength: kotlin.Int? = null

)

