/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package loymax.sdk.models


import com.squareup.moshi.Json

/**
 * Модель верификации нотификатора клиента.
 *
 * @param notifierValue Значение нотификатора.
 */

data class VerificationModel (

    /* Значение нотификатора. */
    @Json(name = "notifierValue")
    var notifierValue: kotlin.String? = null

)

