/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package loymax.sdk.models


import com.squareup.moshi.Json

/**
 * Модель версии.
 *
 * @param major Мажорная версия.
 * @param minor Минорная версия.
 * @param build Билд.
 * @param revision Ревизия.
 */

data class VersionModel (

    /* Мажорная версия. */
    @Json(name = "major")
    var major: kotlin.Int? = null,

    /* Минорная версия. */
    @Json(name = "minor")
    var minor: kotlin.Int? = null,

    /* Билд. */
    @Json(name = "build")
    var build: kotlin.Int? = null,

    /* Ревизия. */
    @Json(name = "revision")
    var revision: kotlin.Int? = null

)

