/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package loymax.sdk.models


import com.squareup.moshi.Json

/**
 * Режим отображения акции (просмотр, редактирование, подтверждение).
 *
 * Values: view,edit,accept
 */

enum class ViewMode(val value: kotlin.String) {

    @Json(name = "View")
    view("View"),

    @Json(name = "Edit")
    edit("Edit"),

    @Json(name = "Accept")
    accept("Accept");

    /**
     * Override toString() to avoid using the enum variable name as the value, and instead use
     * the actual value defined in the API spec file.
     *
     * This solves a problem when the variable name and its value are different, and ensures that
     * the client sends the correct enum values to the server always.
     */
    override fun toString(): String = value

    companion object {
        /**
         * Converts the provided [data] to a [String] on success, null otherwise.
         */
        fun encode(data: kotlin.Any?): kotlin.String? = if (data is ViewMode) "$data" else null

        /**
         * Returns a valid [ViewMode] for [data], null otherwise.
         */
        fun decode(data: kotlin.Any?): ViewMode? = data?.let {
          val normalizedData = "$it".lowercase()
          values().firstOrNull { value ->
            it == value || normalizedData == "$value".lowercase()
          }
        }
    }
}

