/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package loymax.sdk.models

import loymax.sdk.models.KeyValuePairOfInt32AndDecimal
import loymax.sdk.models.MoneyViewModel
import loymax.sdk.models.WithdrawDataType

import com.squareup.moshi.Json

/**
 * ViewModel данных о списании.
 *
 * @param amount 
 * @param positionInfo Распределение изменения баланса по позициям.
 * @param moneyAmount Сумма в деньгах.
 * @param withdrawType 
 * @param description Описание операции.
 */

data class WithdrawDataModel (

    @Json(name = "amount")
    var amount: MoneyViewModel? = null,

    /* Распределение изменения баланса по позициям. */
    @Json(name = "positionInfo")
    var positionInfo: kotlin.collections.MutableList<KeyValuePairOfInt32AndDecimal>? = null,

    /* Сумма в деньгах. */
    @Json(name = "moneyAmount")
    var moneyAmount: kotlin.Double? = null,

    @Json(name = "withdrawType")
    var withdrawType: WithdrawDataType? = null,

    /* Описание операции. */
    @Json(name = "description")
    var description: kotlin.String? = null

)

