/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package loymax.sdk.models


import com.squareup.moshi.Json

/**
 * Действие акции \"Списание бонусов\".
 *
 * @param order Порядковый номер действия в цепочке.
 * @param id Id действия в цепочке.
 * @param amount Сумма изъятия.
 * @param legalCode Код Юридического лица.
 * @param deviceCode Логическое имя дебетовой кассы.
 * @param deviceId Для совместимости, использовать DeviceCode: Код валюты.
 * @param currencyUid Uid валюты.
 * @param currencyExternalId Для совместимости, использовать CurrencyUid: Uid валюты.
 */

data class WithdrawActionDto (

    /* Порядковый номер действия в цепочке. */
    @Json(name = "order")
    var order: kotlin.Int? = null,

    /* Id действия в цепочке. */
    @Json(name = "id")
    var id: kotlin.String? = null,

    /* Сумма изъятия. */
    @Json(name = "amount")
    var amount: kotlin.String? = null,

    /* Код Юридического лица. */
    @Json(name = "legalCode")
    var legalCode: kotlin.String? = null,

    /* Логическое имя дебетовой кассы. */
    @Json(name = "deviceCode")
    var deviceCode: kotlin.String? = null,

    /* Для совместимости, использовать DeviceCode: Код валюты. */
    @Json(name = "deviceId")
    var deviceId: kotlin.String? = null,

    /* Uid валюты. */
    @Json(name = "currencyUid")
    var currencyUid: kotlin.String? = null,

    /* Для совместимости, использовать CurrencyUid: Uid валюты. */
    @Json(name = "currencyExternalId")
    var currencyExternalId: kotlin.String? = null

)

