/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package loymax.sdk.models


import com.squareup.moshi.Json

/**
 * Тип списания.
 *
 * Values: BONUS,GIFT_CARD,WITHDRAW,GIFT_CERTIFICATE,EXPIRATION
 */

enum class WithdrawDataType(val value: kotlin.String) {

    @Json(name = "Bonus")
    BONUS("Bonus"),

    @Json(name = "GiftCard")
    GIFT_CARD("GiftCard"),

    @Json(name = "Withdraw")
    WITHDRAW("Withdraw"),

    @Json(name = "GiftCertificate")
    GIFT_CERTIFICATE("GiftCertificate"),

    @Json(name = "Expiration")
    EXPIRATION("Expiration");

    /**
     * Override toString() to avoid using the enum variable name as the value, and instead use
     * the actual value defined in the API spec file.
     *
     * This solves a problem when the variable name and its value are different, and ensures that
     * the client sends the correct enum values to the server always.
     */
    override fun toString(): String = value

    companion object {
        /**
         * Converts the provided [data] to a [String] on success, null otherwise.
         */
        fun encode(data: kotlin.Any?): kotlin.String? = if (data is WithdrawDataType) "$data" else null

        /**
         * Returns a valid [WithdrawDataType] for [data], null otherwise.
         */
        fun decode(data: kotlin.Any?): WithdrawDataType? = data?.let {
          val normalizedData = "$it".lowercase()
          values().firstOrNull { value ->
            it == value || normalizedData == "$value".lowercase()
          }
        }
    }
}

